"""TrueNorth Range - Cloud-init / cloudbase-init template generator.

Provides role-based cloud-init (Linux) and cloudbase-init (Windows) user-data
templates with Jinja2 support for per-VM customisation.
"""
from __future__ import annotations

import textwrap
from typing import Any


# ======================================================================
# Linux cloud-init templates (YAML)
# ======================================================================

_LINUX_HEADER = textwrap.dedent("""\
    #cloud-config
    # Auto-generated by TrueNorth Range template engine
    hostname: {hostname}
    fqdn: {hostname}.{domain}
    manage_etc_hosts: true

    package_update: true
    package_upgrade: false

""")

_LINUX_MONITORING = textwrap.dedent("""\
    # --- Monitoring agent ---
    runcmd:
      - curl -fsSL https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --dearmor -o /usr/share/keyrings/wazuh.gpg || true
      - echo "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main" > /etc/apt/sources.list.d/wazuh.list || true
""")

_ROLE_TEMPLATES: dict[str, str] = {
    "domain_controller": textwrap.dedent("""\
        packages:
          - samba
          - samba-dsdb-modules
          - samba-vfs-modules
          - krb5-user
          - krb5-config
          - winbind
          - libnss-winbind
          - libpam-winbind
          - acl
          - dnsutils

        runcmd:
          - systemctl stop smbd nmbd winbind || true
          - mv /etc/samba/smb.conf /etc/samba/smb.conf.bak || true
          - >-
            samba-tool domain provision
            --realm={domain_upper}
            --domain={domain_short}
            --server-role=dc
            --dns-backend=SAMBA_INTERNAL
            --adminpass='TN_P@ssw0rd!'
            --use-rfc2307
          - cp /var/lib/samba/private/krb5.conf /etc/krb5.conf
          - systemctl unmask samba-ad-dc
          - systemctl enable --now samba-ad-dc
          - samba-tool user create trainee 'Tr@inee1!' --given-name=Test --surname=Trainee || true
          - samba-tool group addmembers 'Domain Users' trainee || true
    """),

    "workstation": textwrap.dedent("""\
        packages:
          - samba-common
          - krb5-user
          - realmd
          - sssd
          - adcli
          - xrdp
          - firefox
          - libreoffice-calc
          - net-tools
          - curl

        runcmd:
          - systemctl enable --now xrdp
          - echo '{domain_upper}' | realm join --user=administrator --stdin {domain} || true
          - useradd -m -s /bin/bash trainee || true
          - echo 'trainee:Tr@inee1!' | chpasswd
    """),

    "web_server": textwrap.dedent("""\
        packages:
          - nginx
          - php-fpm
          - php-mysql
          - certbot
          - curl

        write_files:
          - path: /var/www/html/index.html
            content: |
              <!DOCTYPE html>
              <html><body><h1>TrueNorth Range — {hostname}</h1></body></html>
            permissions: '0644'

        runcmd:
          - systemctl enable --now nginx
    """),

    "db_server": textwrap.dedent("""\
        packages:
          - postgresql
          - postgresql-contrib
          - postgresql-client

        runcmd:
          - systemctl enable --now postgresql
          - sudo -u postgres createuser --superuser tnadmin || true
          - sudo -u postgres createdb --owner=tnadmin truenorth_data || true
          - sudo -u postgres psql -c "ALTER USER tnadmin PASSWORD 'TN_Db_P@ss!';" || true
    """),

    "jump_box": textwrap.dedent("""\
        packages:
          - xrdp
          - openssh-server
          - tmux
          - screen
          - auditd
          - rsyslog

        runcmd:
          - systemctl enable --now xrdp
          - systemctl enable --now sshd
          - systemctl enable --now auditd
          - auditctl -w /var/log -p wa -k log_access || true
          - auditctl -w /etc/passwd -p wa -k user_changes || true
          - echo 'AllowTcpForwarding yes' >> /etc/ssh/sshd_config
          - systemctl restart sshd
    """),

    "siem": textwrap.dedent("""\
        packages:
          - docker.io
          - docker-compose
          - curl
          - jq

        runcmd:
          - systemctl enable --now docker
          - mkdir -p /opt/wazuh && cd /opt/wazuh
          - >-
            curl -fsSL https://packages.wazuh.com/4.9/wazuh-install.sh -o wazuh-install.sh
            && chmod +x wazuh-install.sh || true
          - echo "Wazuh/OpenSearch install placeholder — run wazuh-install.sh manually"
    """),

    "ids": textwrap.dedent("""\
        packages:
          - suricata
          - zeek
          - jq
          - tcpdump

        runcmd:
          - suricata-update || true
          - systemctl enable --now suricata || true
          - echo "IDS rules loaded — tune /etc/suricata/suricata.yaml for range networks"
    """),

    "attacker": textwrap.dedent("""\
        packages:
          - python3
          - python3-pip
          - python3-venv
          - git
          - nmap
          - curl
          - jq
          - golang

        runcmd:
          - python3 -m venv /opt/caldera-venv
          - /opt/caldera-venv/bin/pip install --quiet requests pyyaml
          - >-
            git clone --depth 1 https://github.com/mitre/caldera.git /opt/caldera || true
          - echo "Caldera agent placeholder — configure server URL in /opt/caldera/conf"
          - >-
            mkdir -p /opt/tools
            && curl -fsSL https://raw.githubusercontent.com/rapid7/metasploit-framework/master/README.md
            -o /opt/tools/msf-readme.md || true
          - echo "Metasploit placeholder — install via msfinstall if needed"
    """),
}

# ======================================================================
# Windows cloudbase-init templates (PowerShell)
# ======================================================================

_WINDOWS_HEADER = textwrap.dedent("""\
    #ps1_sysnative
    # Auto-generated by TrueNorth Range template engine
    # Cloudbase-init userdata for {hostname}

    $hostname = "{hostname}"
    $domain   = "{domain}"
    $ErrorActionPreference = "Continue"

    # Set hostname
    Rename-Computer -NewName $hostname -Force -ErrorAction SilentlyContinue

""")

_WINDOWS_ROLE_TEMPLATES: dict[str, str] = {
    "domain_controller": textwrap.dedent("""\
        # Install AD DS
        Install-WindowsFeature -Name AD-Domain-Services -IncludeManagementTools
        Import-Module ADDSDeployment
        Install-ADDSForest `
            -DomainName "{domain}" `
            -DomainNetbiosName "{domain_short}" `
            -SafeModeAdministratorPassword (ConvertTo-SecureString 'TN_P@ssw0rd!' -AsPlainText -Force) `
            -InstallDns `
            -Force

        # Create trainee user after reboot
        $trigger = New-ScheduledTaskTrigger -AtStartup
        $action  = New-ScheduledTaskAction -Execute "powershell.exe" -Argument @"
        Import-Module ActiveDirectory
        New-ADUser -Name 'trainee' -AccountPassword (ConvertTo-SecureString 'Tr@inee1!' -AsPlainText -Force) -Enabled `$true -ErrorAction SilentlyContinue
        "@
        Register-ScheduledTask -TaskName "CreateTrainee" -Trigger $trigger -Action $action -RunLevel Highest -User "SYSTEM" -ErrorAction SilentlyContinue
    """),

    "workstation": textwrap.dedent("""\
        # Join domain
        $cred = New-Object PSCredential("administrator@{domain}", (ConvertTo-SecureString 'TN_P@ssw0rd!' -AsPlainText -Force))
        Add-Computer -DomainName "{domain}" -Credential $cred -OUPath "OU=Workstations,DC={dc_parts}" -Restart -Force -ErrorAction SilentlyContinue

        # Install tools
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Invoke-WebRequest -Uri "https://community.chocolatey.org/install.ps1" -UseBasicParsing | Invoke-Expression
        choco install -y firefox 7zip notepadplusplus sysinternals
    """),

    "web_server": textwrap.dedent("""\
        Install-WindowsFeature -Name Web-Server -IncludeManagementTools
        Set-Content -Path "C:\\inetpub\\wwwroot\\index.html" -Value "<html><body><h1>TrueNorth Range - {hostname}</h1></body></html>"
    """),

    "db_server": textwrap.dedent("""\
        # SQL Server placeholder — typically deployed from template image
        Write-Host "DB Server {hostname} — configure SQL Server post-deployment"
    """),

    "jump_box": textwrap.dedent("""\
        # Enable RDP
        Set-ItemProperty -Path "HKLM:\\System\\CurrentControlSet\\Control\\Terminal Server" -Name fDenyTSConnections -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

        # Enable auditing
        auditpol /set /subcategory:"Logon" /success:enable /failure:enable
        auditpol /set /subcategory:"Logoff" /success:enable
        auditpol /set /subcategory:"File System" /success:enable /failure:enable

        # Install OpenSSH
        Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0 -ErrorAction SilentlyContinue
        Start-Service sshd -ErrorAction SilentlyContinue
        Set-Service -Name sshd -StartupType Automatic
    """),
}

_WINDOWS_MONITORING = textwrap.dedent("""\
    # --- Monitoring agent ---
    # Wazuh agent placeholder
    Write-Host "Install Wazuh agent from https://packages.wazuh.com/4.x/windows/wazuh-agent.msi"
""")


# ======================================================================
# Generator class
# ======================================================================

class CloudInitGenerator:
    """Generate cloud-init (Linux) or cloudbase-init (Windows) user-data."""

    def generate(
        self,
        role: str,
        hostname: str,
        ip: str = "",
        domain: str = "corp.truenorth.local",
        os_type: str = "linux",
        services: list[str] | None = None,
    ) -> str:
        """Return the complete user-data string for a VM.

        Parameters
        ----------
        role:
            VM role (domain_controller, workstation, web_server, etc.)
        hostname:
            Desired hostname for the VM.
        ip:
            Static IP assignment (informational, used in comments).
        domain:
            AD / DNS domain name.
        os_type:
            ``'linux'`` or ``'windows'``.
        services:
            Optional list of services the VM should run.
        """
        fmt = self._format_vars(hostname, domain)

        if os_type == "windows":
            return self._render_windows(role, fmt)
        return self._render_linux(role, fmt)

    # ------------------------------------------------------------------

    @staticmethod
    def _format_vars(hostname: str, domain: str) -> dict[str, str]:
        parts = domain.split(".")
        return {
            "hostname": hostname,
            "domain": domain,
            "domain_upper": domain.upper(),
            "domain_short": parts[0].upper() if parts else "CORP",
            "dc_parts": ",DC=".join(parts),
        }

    def _render_linux(self, role: str, fmt: dict[str, str]) -> str:
        header = _LINUX_HEADER.format(**fmt)
        body = _ROLE_TEMPLATES.get(role, "# Generic Linux VM\npackages:\n  - curl\n  - net-tools\n")
        body = body.format(**fmt)
        monitoring = _LINUX_MONITORING.format(**fmt)
        return header + body + "\n" + monitoring

    def _render_windows(self, role: str, fmt: dict[str, str]) -> str:
        header = _WINDOWS_HEADER.format(**fmt)
        body = _WINDOWS_ROLE_TEMPLATES.get(role, '# Generic Windows VM\nWrite-Host "Provisioned {hostname}"'.format(**fmt) + "\n")
        body = body.format(**fmt)
        monitoring = _WINDOWS_MONITORING.format(**fmt)
        return header + body + "\n" + monitoring