"""Shared fixture for the ARC² contract tests: a tiny repo root with a four-row crosswalk, one
course that already delivers PO_009, and the range the fixture manifest reuses."""

from __future__ import annotations

import json
from pathlib import Path

import pytest
import yaml
from arc2 import check

CROSSWALK = """qsp_code,nqual,tier,po_id,po_title,eos,conditions,critical_events,assessment_type,duration_min,pass_standard,deliverable,environment,target_role,nice_dcwf_task,component_version,scenario_count,build_hours,status
ALJQ,ALJQ,core,PO_007,Analyze Malicious Activity in Network Traffic,007.01,pcap,scanning;exfiltration;lateral_movement,PC practical,240,P/F,report,COTE,Cyber Defense Analyst,T0023,SP800-181r1,4,200,todo
ALJQ,ALJQ,core,PO_009,Security Monitoring,009.01,siem,alert_triage;escalation,PC practical,180,P/F,report,COTE,Cyber Defense Analyst,T0023,SP800-181r1,2,80,todo
ALJQ,ALJQ,core,PO_010,Example,010.01,siem,example_event,PC practical,60,P/F,report,COTE,Analyst,T0023,SP800-181r1,1,10,example
TEMP64,TEMP64,core,PO_001-003,Gain Access,001,lab,initial_access,PC practical,240,P/F,report,COTE,Operator,T0028,SP800-181r1,3,100,offensive_author
"""

CLAIMING_COURSE = """course_code: C204
title: Security Monitoring
modules:
- ordinal: 1
  title: SIEM
  po:
    qsp_code: ALJQ
    po_code: PO_009
"""


CATALOGUE = """programme,institution,dp_order,qsp_code,term_code,term_label,term_start,term_end,weeks,course_code,course_title,duration_hours,prerequisites,provenance,status
cyber-operator,Algonquin College,1,QSP-TODO,DP1-Y1-F,DP 1 Year 1 Fall,2026-09-01,2026-12-31,15,C101,Computer Architecture & Systems,,,unsourced,proposed
"""

REFERENCES = """references:
  nist-sp-800-92:
    title: Guide to Computer Security Log Management
    publisher: NIST
    year: 2006
    url: https://csrc.nist.gov/pubs/sp/800/92/final
  mitre-attack:
    title: MITRE ATT&CK Enterprise
    publisher: MITRE
    year: 2024
    url: https://attack.mitre.org/
"""

VM_CATALOGUE = """template_id,os_family,version,role,reuse_tier,enabled,build_hours,golden_gb,sensor_baked,notes
win-xp-sp3,windows,XP SP3,legacy victim,med,no,10,12,no,disabled
srv2019,windows,2019,server,high,yes,8,40,yes,
win10-22h2,windows,10 22H2,workstation,high,yes,6,30,yes,
securityonion,linux,2.4,sensor,high,yes,6,60,yes,
"""


# ── the content a run's stages write; make_run() lays these down so the QA depth checks see
# real files rather than placeholders ──────────────────────────────────────────────────

QUESTIONS = [
    ("Which Windows event id records a successful network logon?", ["4624", "4625", "4688", "7045"], "A"),
    ("Which protocol carries admin share access between Windows hosts?", ["SMB", "SNMP", "NTP", "DHCP"], "A"),
    (
        "Which artefact best evidences a pass-the-hash logon?",
        ["Kerberos AS-REQ", "NTLM logon type 3 without password", "DNS query", "ARP reply"],
        "B",
    ),
    (
        "Where does a helpdesk RDP session usually originate?",
        ["A ticketed admin host", "A printer", "The domain controller", "A guest VLAN"],
        "A",
    ),
    (
        "What distinguishes backup SMB traffic from lateral movement?",
        ["Scheduled, same source, large sequential reads", "Random ports", "IPv6 only", "No authentication"],
        "A",
    ),
]


def course_yaml() -> str:
    doc = {
        "course_code": "ARC2-ADLM",
        "title": "Detecting AD Lateral Movement",
        "version": "1.0",
        "difficulty": "intermediate",
        "duration_hours": 8,
        "provenance": "unsourced",
        "status": "draft",
        "is_published": False,
        "qsp_code": "ALJQ",
        "source": {
            "origin": "ARC2 generated draft",
            "notes": ["Generated by ARC2. Module-to-PO mapping is PROPOSED, not standards-validated."],
        },
        "modules": [
            {
                "ordinal": 1,
                "title": "Lateral movement",
                "content_type": "reading",
                "duration_minutes": 60,
                "is_required": True,
                "pass_threshold": 70,
                "objectives": ["Detect lateral movement from authentication telemetry"],
                "topics": ["Authentication telemetry", "SMB admin shares"],
                "lab": "Review the captured authentication and SMB telemetry and identify the lateral movement.",
                "refs": ["nist-sp-800-92"],
                "quiz": {
                    "title": "Quiz 1",
                    "pass_threshold": 70,
                    "questions": [{"question": q, "options": o, "answer": a} for q, o, a in QUESTIONS],
                },
            }
        ],
    }
    return yaml.safe_dump(doc, sort_keys=False, allow_unicode=True)


TIMELINE = """scenario:
  po_id: PO_TODO
  title: "Detecting AD Lateral Movement"
  environment: COTE
  duration_min: 480
  range_template: ../range.tf
  golden_templates: [srv2019, win10-22h2, securityonion]
  injects:
    - id: inj-01
      t_offset_min: 10
      attack_technique: T1021.002
      description: "Pre-captured SMB admin-share session from a workstation to the file server"
      critical: true
  noise_floor:
    - id: n1
      description: Backup agent SMB traffic
      why_plausible: Runs nightly on every server
    - id: n2
      description: Helpdesk RDP session
      why_plausible: Ticketed remote support
  validators:
    - validators/crit_lateral_movement.md
    - validators/manual_ack_summative.md
  variant: ../04-artifacts/variant_B/timeline.yaml
"""

SCENARIO = """name: arc2-adlm
version: "1.0"
range_template: soc-training
timeline:
  - t: "00:10"
    action: inject
    params: {id: inj-01}
objectives:
  - id: M01-O01
    type: detection
    validator: crit_ce01
    points: 1
"""

CATALOGUE_ROW = (
    "programme,institution,dp_order,qsp_code,term_code,term_label,term_start,term_end,weeks,course_code,course_title,duration_hours,prerequisites,provenance,status\n"
    "cyber-operator,Algonquin College,1,QSP-TODO,,,,,,ARC2-ADLM,Detecting AD Lateral Movement,8,,unsourced,proposed\n"
)


def module_config(module: dict, code: str = "ARC2-ADLM") -> dict:
    """A course-config.json that agrees with the derived cmi5 block for this module."""
    from arc2 import cmi5

    ids = cmi5.publisher_ids(code, module["id"], module["objective_ids"])
    questions = [{"id": f"q{i}", "stem": q, "options": o, "answer": a} for i, (q, o, a) in enumerate(QUESTIONS, 1)]
    return {
        "schema": cmi5.CONFIG_SCHEMA,
        "module_id": module["id"],
        "ordinal": module["ordinal"],
        "title": module["title"],
        "au_id": ids["au_id"],
        "objective_ids": list(module["objective_ids"]),
        "objectives": [
            {"id": o, "text": "Detect lateral movement", "iri": ids["objective_iris"][o]}
            for o in module["objective_ids"]
        ],
        "moveOn": "Passed" if module["quiz"] else "Completed",
        "masteryScore": cmi5.mastery_score(module),
        "lang": "en-CA",
        "content": {"pages": [f"content/{Path(p).name}" for p in module["pages"]], "lab": None},
        "quiz": {"title": "Quiz 1", "pass_threshold": module["quiz"]["pass_threshold"], "questions": questions}
        if module["quiz"]
        else None,
        "media": {"images": [], "videos": []},
    }


def write_run_content(run: Path, manifest: dict) -> None:
    """The files the QA depth checks parse, matching full_manifest() in test_arc2_manifest."""
    content = manifest.get("content")
    if content:
        (run / content["course_yaml"]).write_text(course_yaml())
        for m in content["modules"]:
            (run / m["config"]).write_text(json.dumps(module_config(m), indent=2))
    (run / "01-blueprint" / "catalogue_row.csv").write_text(CATALOGUE_ROW)
    if manifest.get("injects"):
        (run / manifest["injects"]["timeline"]).write_text(TIMELINE)
    if manifest.get("scenario"):
        (run / manifest["scenario"]["path"]).write_text(SCENARIO)


@pytest.fixture
def repo(tmp_path: Path) -> Path:
    root = tmp_path / "repo"
    (root / check.CROSSWALK_REL).parent.mkdir(parents=True)
    (root / check.CROSSWALK_REL).write_text(CROSSWALK)
    (root / check.COURSES_REL).mkdir(parents=True)
    (root / check.COURSES_REL / "c204.yaml").write_text(CLAIMING_COURSE)
    (root / "content" / "ranges" / "soc-training").mkdir(parents=True)  # the range full_manifest() reuses
    (root / "content" / "catalogue").mkdir(parents=True)
    (root / "content" / "catalogue" / "cyber_operator_programme.csv").write_text(CATALOGUE)
    (root / "content" / "catalogue" / "references.yaml").write_text(REFERENCES)
    (root / check.CROSSWALK_REL).with_name("vm_catalogue.csv").write_text(VM_CATALOGUE)
    return root
