"""gs-core: the VM a hypervisor backend runs a range's Greyspace stack on (ADR 0007, slice 0).

``host_vm(range_id, block, template)`` turns a range's Greyspace block into one more
rendered VM for the build, ``gs-core``:

* cloned from the golden image GREYSPACE_HOST_TEMPLATE (default ``greyspace-host``: Ubuntu
  LTS + Docker + nfs-common + open-vm-tools with every stack image pre-loaded, built by
  greyspace/host/prepare-host.sh), or the Content Library item of that name;
* one NIC on the template's Greyspace network (the block's ``network``, default
  ``greyspace``), at that subnet's last usable address, its gateway the range router
  that also has a NIC there;
* cloud-init (VMware guestinfo) carrying a service account for the configure stage and
  ``/opt/greyspace/bootstrap.sh``, which at first boot unpacks the **bundle**: the stack
  rendered for this block (greyspace_runtime.config.render, ``host=True``) plus, for T0,
  the corpus itself. The bundle travels in ``guestinfo.tn.greyspace.bundle.<n>`` chunks
  (a VMX value is capped well below a bundle), read back in the guest with vmware-rpctool.

The router with a NIC on that network is given ``greyspace_route`` (the public prefix,
gs-core's address, the resolver) so its configuration (vyos_config.py) routes the
simulated internet to gs-core and lets the range's zones reach it.

The configure stage (worker/greyspace.py ``configure``) then logs in through the
backend's guest channel and runs ``bootstrap.sh configure`` (mount the corpus read-only,
``bin/gs up``) and ``bin/gs health``.

The service account's password is never stored: it is derived from TN_SECRETS_KEY and the
range id (HMAC), so the configure stage and breadcrumb deliveries can log in again for
the range's life, and the guestinfo holds only its SHA-512 crypt hash. Rotating
TN_SECRETS_KEY (its first key) changes the password ranges built before were given:
rebuild their Greyspace.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import io
import ipaddress
import json
import os
import tarfile
import warnings
from pathlib import Path

from . import secretbox
from .greyspace_runtime import config, fixture
from .greyspace_runtime.manifest import Manifest, ManifestError, parse_manifest
from .provisioners.base import GuestLogin, GuestStep

HOST_NODE = "gs-core"
ROOT = "/opt/greyspace"
STACK_DIR = f"{ROOT}/stack"
CORPUS_DIR = "/srv/greyspace/corpus"
IMAGES_DIR = f"{ROOT}/images"
SERVICE_USER = "tn-greyspace"
CHUNK = 45_000  # base64 characters per guestinfo value (vyos_config: VMX values stay under 60 kB)
MAX_BUNDLE_B64 = 1_500_000  # the whole bundle in guestinfo; a bigger corpus belongs on NFS
PROJECT = "greyspace"
SUDO = "/usr/bin/sudo"
GS = f"/usr/bin/python3 {STACK_DIR}/bin/gs"

BOOTSTRAP = r"""#!/bin/bash
# Greyspace host bootstrap (generated by the TrueNorth worker, worker/greyspace_host.py).
#   bootstrap.sh unpack      first boot (cloud-init): the bundle from guestinfo -> /opt/greyspace
#   bootstrap.sh configure   the configure stage: corpus (NFS read-only, or the bundled T0) + gs up
set -euo pipefail
ROOT=/opt/greyspace
CORPUS=/srv/greyspace/corpus
log() { echo "greyspace-bootstrap: $*" | tee -a /var/log/greyspace-bootstrap.log; }
get() { vmware-rpctool "info-get guestinfo.tn.greyspace.$1"; }

unpack() {
  local count sha b64 i
  count="$(get bundle.count)"
  sha="$(get bundle.sha256)"
  b64=""
  for ((i = 0; i < count; i++)); do b64+="$(get "bundle.$i")"; done
  printf '%s' "$b64" | base64 -d > "$ROOT/bundle.tgz"
  echo "$sha  $ROOT/bundle.tgz" | sha256sum -c --quiet
  rm -rf "$ROOT/stack" "$ROOT/corpus"
  tar -xzf "$ROOT/bundle.tgz" -C "$ROOT"
  chmod 0755 "$ROOT/stack/bin/gs"
  log "unpacked $(find "$ROOT/stack" -type f | wc -l) stack files"
}

configure() {
  # shellcheck disable=SC1091
  source "$ROOT/host.env"
  mkdir -p "$CORPUS"
  if [[ -n "${GS_CORPUS_NFS:-}" ]]; then
    # A published NetApp snapshot was verified when it was published (docs/greyspace-corpus.md);
    # re-hashing terabytes here would hold the range for hours.
    python3 "$ROOT/stack/bin/gs" corpus mount --source "$GS_CORPUS_NFS" --dir "$CORPUS"
    test -s "$CORPUS/manifest.json"
  elif [[ -d "$ROOT/corpus" ]]; then
    rm -rf "$CORPUS" && mkdir -p "$(dirname "$CORPUS")" && cp -a "$ROOT/corpus" "$CORPUS"
    python3 "$ROOT/stack/bin/gs" corpus verify "$CORPUS"
  fi
  python3 "$ROOT/stack/bin/gs" up
  log "stack up"
}

case "${1:-}" in
  unpack) unpack ;;
  configure) configure ;;
  *) echo "usage: bootstrap.sh unpack|configure" >&2; exit 2 ;;
esac
"""


class HostPlanError(ValueError):
    """The range's Greyspace block cannot be given a gs-core VM (and why)."""


def host_template() -> str:
    return os.getenv("GREYSPACE_HOST_TEMPLATE", "greyspace-host").strip() or "greyspace-host"


def corpus_nfs() -> str:
    """``server:/export`` of the corpus volume (NetApp), mounted read-only; empty: bundle T0."""
    return os.getenv("GREYSPACE_CORPUS_NFS", "").strip()


def host_specs() -> dict:
    def num(name: str, default: int) -> int:
        try:
            return max(1, int(os.getenv(name, str(default))))
        except ValueError:
            return default

    return {"cores": num("GREYSPACE_HOST_CORES", 4), "memory_mb": num("GREYSPACE_HOST_MEMORY_MB", 8192),
            "disk_gb": num("GREYSPACE_HOST_DISK_GB", 80)}


def host_password(range_id: str) -> str:
    """The gs-core service account's password for this range (HMAC of TN_SECRETS_KEY)."""
    keys = [k.strip() for k in os.getenv(secretbox.KEY_ENV, "").split(",") if k.strip()]
    if not keys or len(keys[0]) < secretbox.MIN_KEY_LENGTH:
        raise HostPlanError(f"{secretbox.KEY_ENV} is unset or too short: gs-core's service account needs it")
    mac = hmac.new(keys[0].encode(), f"greyspace-host:{range_id}".encode(), hashlib.sha256).digest()
    return base64.urlsafe_b64encode(mac).decode().rstrip("=")[:32] + "-G1a"


def login(range_id: str) -> GuestLogin:
    return GuestLogin(SERVICE_USER, host_password(range_id), "linux")


def _sha512_crypt(password: str) -> str | None:
    try:
        with warnings.catch_warnings():
            warnings.simplefilter("ignore", DeprecationWarning)
            import crypt  # removed in Python 3.13; the worker image runs 3.11
        hashed = crypt.crypt(password, crypt.mksalt(crypt.METHOD_SHA512))
    except Exception:  # noqa: BLE001
        return None
    return hashed if hashed and hashed.startswith("$6$") else None


def load_manifest(tier: str) -> Manifest | None:
    """``$GREYSPACE_MANIFEST_DIR/<tier>/manifest.json``, else the built-in T0 fixture for t0
    (the same lookup as the API's app/greyspace/service.py)."""
    root = os.getenv("GREYSPACE_MANIFEST_DIR", "").strip()
    if root:
        path = Path(root) / tier / "manifest.json"
        if path.is_file():
            try:
                return parse_manifest(json.loads(path.read_text(encoding="utf-8")))
            except (OSError, ValueError, ManifestError):
                return None
    return parse_manifest(fixture.t0_manifest_doc()) if tier == "t0" else None


def params_of(block: dict) -> config.BlockParams:
    packs = block.get("site_packs")
    return config.BlockParams(
        corpus_tier=str(block.get("corpus_tier") or "t0"),
        site_packs=tuple(packs) if packs is not None else None,
        public_prefix=block.get("public_prefix"),
        npc_profile=str(block.get("npc_profile") or "off"),
        threat_infra=bool(block.get("threat_infra", True)),
        trust_ca=bool(block.get("trust_ca", True)),
    )


def render(block: dict) -> tuple[Manifest, config.Rendered]:
    manifest = load_manifest(str(block.get("corpus_tier") or "t0"))
    if manifest is None:
        raise HostPlanError(f"the {block.get('corpus_tier')} corpus manifest is not readable by the worker "
                            "(GREYSPACE_MANIFEST_DIR)")
    try:
        rendered = config.render(manifest, params_of(block), corpus_dir=CORPUS_DIR, images_dir=IMAGES_DIR,
                                 host=True, project=PROJECT)
    except config.ConfigError as exc:
        raise HostPlanError(str(exc)) from exc
    return manifest, rendered


def bundle(manifest: Manifest, rendered: config.Rendered, *, with_corpus: bool) -> bytes:
    """``stack/`` (the rendered files) and, ``with_corpus``, ``corpus/`` (T0 only), as tar.gz."""
    buf = io.BytesIO()

    def add(name: str, data: bytes, mode: int = 0o644) -> None:
        info = tarfile.TarInfo(name)
        info.size, info.mode, info.mtime = len(data), mode, 0
        tar.addfile(info, io.BytesIO(data))

    with tarfile.open(fileobj=buf, mode="w:gz", compresslevel=9) as tar:
        for rel, text in sorted(rendered.files.items()):
            add(f"stack/{rel}", text.encode("utf-8"), 0o755 if rel.endswith(".sh") or rel == "bin/gs" else 0o644)
        if with_corpus:
            if manifest.tier != "t0":
                raise HostPlanError(f"the {manifest.tier} corpus is not bundled: set GREYSPACE_CORPUS_NFS")
            doc = fixture.t0_manifest_doc()
            doc["videos"] = []  # no ffmpeg in the worker: the T0 test-pattern video is CI-only
            lines = []
            for fqdn, category, title, tagline in fixture.SITES:
                for rel, data in sorted(fixture.site_files(fqdn, category, title, tagline).items()):
                    path = f"sites/{fqdn}/{rel}"
                    add(f"corpus/{path}", data)
                    lines.append(f"{hashlib.sha256(data).hexdigest()}  {path}\n")
            add("corpus/manifest.json", (json.dumps(doc, indent=2) + "\n").encode())
            add("corpus/checksums.sha256", "".join(lines).encode())
    return buf.getvalue()


def guestinfo_bundle(data: bytes) -> dict[str, str]:
    b64 = base64.b64encode(data).decode("ascii")
    if len(b64) > MAX_BUNDLE_B64:
        raise HostPlanError(f"the Greyspace bundle is {len(b64)} bytes in base64, over {MAX_BUNDLE_B64}: "
                            "serve the corpus over NFS (GREYSPACE_CORPUS_NFS)")
    chunks = [b64[i:i + CHUNK] for i in range(0, len(b64), CHUNK)]
    out = {f"guestinfo.tn.greyspace.bundle.{n}": c for n, c in enumerate(chunks)}
    out["guestinfo.tn.greyspace.bundle.count"] = str(len(chunks))
    out["guestinfo.tn.greyspace.bundle.sha256"] = hashlib.sha256(data).hexdigest()
    return out


def cloud_config(range_id: str) -> dict:
    password = host_password(range_id)
    user: dict = {
        "name": SERVICE_USER,
        "gecos": "TrueNorth Greyspace configure account",
        "shell": "/bin/bash",
        "sudo": "ALL=(ALL) NOPASSWD:ALL",
        "groups": ["docker"],
        "lock_passwd": False,
    }
    hashed = _sha512_crypt(password)
    if hashed:
        user["hashed_passwd"] = hashed
    else:
        user["plain_text_passwd"] = password
    return {
        "users": [user],
        "write_files": [
            {"path": f"{ROOT}/bootstrap.sh", "permissions": "0755", "content": BOOTSTRAP},
            {"path": f"{ROOT}/host.env", "permissions": "0644", "content": f"GS_CORPUS_NFS={corpus_nfs()}\n"},
        ],
        "runcmd": [[f"{ROOT}/bootstrap.sh", "unpack"]],
    }


def _host_address(net: ipaddress.IPv4Network, taken: set[str]) -> str:
    last = int(net.broadcast_address) - 1
    for addr in range(last, int(net.network_address) + 1, -1):
        ip = str(ipaddress.IPv4Address(addr))
        if ip not in taken:
            return ip
    raise HostPlanError(f"no free address for gs-core in {net}")


def host_vm(range_id: str, block: dict, template: dict) -> tuple[dict, dict]:
    """(gs-core's rendered VM, what to record about it). Raises HostPlanError."""
    network = str(block.get("network") or "greyspace")
    net_def = next((n for n in template.get("networks") or [] if n.get("name") == network), None)
    if net_def is None:
        raise HostPlanError(
            f"the template has no network named {network!r}: add a VLAN of that name and give the range's "
            "edge router an interface on it (gs-core joins it there)"
        )
    try:
        cidr = ipaddress.IPv4Network(str(net_def.get("cidr")), strict=False)
    except ValueError as exc:
        raise HostPlanError(f"network {network!r} has no usable CIDR") from exc
    taken = {str(n.get("ip")) for v in template.get("vms") or [] for n in v.get("nics") or []} | {
        str(v.get("ip")) for v in template.get("vms") or []}
    gateway = str(net_def.get("gateway") or "")
    ip = _host_address(cidr, taken | {gateway})
    manifest, rendered = render(block)
    data = bundle(manifest, rendered, with_corpus=not corpus_nfs())
    specs = host_specs()
    vid = net_def.get("vlan_id")
    nic = {"vlan": vid, "network": network, "ip": ip, "prefix": cidr.prefixlen, "netmask": str(cidr.netmask),
           "gateway": gateway}
    if net_def.get("port_group"):
        nic["port_group"] = net_def["port_group"]
    vm = {
        "name": f"{range_id[:8]}-{HOST_NODE}",
        "node_id": HOST_NODE,
        "role": "greyspace",
        "os": "ubuntu-24.04",
        "template_name": host_template(),
        "vlan_id": vid, "vlan_tag": vid, "ip": ip, "gateway": gateway, "netmask": str(cidr.netmask),
        "prefix": cidr.prefixlen, "port_group": net_def.get("port_group", ""),
        "nics": [nic],
        "cores": specs["cores"], "memory": specs["memory_mb"], "memory_mb": specs["memory_mb"],
        "disk_gb": specs["disk_gb"], "services": [],
        "dns": [rendered.summary["address_plan"]["resolver"]],
        "cloud_config": cloud_config(range_id),
        "guestinfo": guestinfo_bundle(data),
    }
    info = {
        "host": vm["name"], "ip": ip, "network": network, "template": host_template(),
        "public": rendered.summary["address_plan"]["public"], "resolver": rendered.summary["address_plan"]["resolver"],
        "corpus": f"nfs {corpus_nfs()}" if corpus_nfs() else f"bundled {manifest.tier} {manifest.version}",
        "bundle_bytes": len(data), "services": rendered.summary["services"],
        "router": gateway or None,
    }
    return vm, info


def route_router(template: dict, info: dict) -> str | None:
    """Give the router whose NIC on gs-core's network is that network's gateway the route to
    the simulated internet (vyos_config.py reads ``greyspace_route``). Returns its name."""
    for vm in template.get("vms") or []:
        if any(n.get("network") == info["network"] and n.get("ip") and n.get("ip") == info["router"]
               for n in vm.get("nics") or []):
            vm["greyspace_route"] = {"prefix": info["public"], "via": info["ip"], "resolver": info["resolver"],
                                     "network": info["network"]}
            return str(vm.get("name"))
    return None


def configure_steps() -> list[GuestStep]:
    return [
        GuestStep("cloud-init", SUDO, '-n /bin/sh -c "cloud-init status --wait >/dev/null 2>&1 || true"'),
        GuestStep("configure", SUDO, f"-n {ROOT}/bootstrap.sh configure"),
        GuestStep("health", SUDO, f"-n {GS} health --json"),
    ]


def crumb_steps(op: dict) -> list[GuestStep]:
    """The guest command(s) for a breadcrumb operation from the greyspace_breadcrumb injector."""
    if op.get("operation") == "remove":
        exercise = str(op.get("exercise") or "")
        ids = op.get("ids")
        if ids is None:
            return [GuestStep("crumb-remove", SUDO, f"-n {GS} crumb remove --exercise {exercise}")]
        return [GuestStep(f"crumb-remove-{i}", SUDO, f"-n {GS} crumb remove --exercise {exercise} --id {i}")
                for i in ids]
    b64 = base64.b64encode(json.dumps(op["payload"], separators=(",", ":")).encode()).decode()
    if len(b64) > 60_000:
        raise HostPlanError("the breadcrumb payload is too large for one guest command (keep crumbs under ~40 kB)")
    return [GuestStep("crumb-plant", SUDO, f"-n {GS} crumb plant --b64 {b64}")]
