"""GENERATED by scripts/export_worker_tables.py from control-plane/api/app/models.py. Do not edit.

The API-owned tables the worker may read and write (Core, not ORM). Only column names
and types are mirrored: Python-side defaults (ids, timestamps) are NOT, so supply them
explicitly on insert. To use another table, add it to WORKER_TABLES in the script.
"""

from __future__ import annotations

import uuid

import sqlalchemy as sa
from sqlalchemy import CHAR, TypeDecorator
from sqlalchemy.dialects.postgresql import UUID as PG_UUID

metadata = sa.MetaData()


class GUID(TypeDecorator):
    """Platform-independent GUID: CHAR(36) on SQLite, native UUID on Postgres."""

    impl = CHAR(36)
    cache_ok = True

    def load_dialect_impl(self, dialect):
        if dialect.name == "postgresql":
            return dialect.type_descriptor(PG_UUID(as_uuid=True))
        return dialect.type_descriptor(CHAR(36))

    def process_bind_param(self, value, dialect):
        if value is None:
            return value
        if dialect.name == "postgresql":
            return value if isinstance(value, uuid.UUID) else uuid.UUID(value)
        return str(value) if isinstance(value, uuid.UUID) else value

    def process_result_value(self, value, dialect):
        if value is None:
            return value
        if isinstance(value, uuid.UUID):
            return value
        return uuid.UUID(str(value))


after_action_reports = sa.Table(
    "after_action_reports",
    metadata,
    sa.Column("id", GUID(), primary_key=True),
    sa.Column("exercise_id", GUID(), nullable=False, unique=True),
    sa.Column("report_json", sa.Text(), nullable=False),
    sa.Column("report_html", sa.Text()),
    sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
)

competencies = sa.Table(
    "competencies",
    metadata,
    sa.Column("id", GUID(), primary_key=True),
    sa.Column("code", sa.String(100), nullable=False),
    sa.Column("name", sa.String(255), nullable=False),
    sa.Column("description", sa.Text(), nullable=False),
    sa.Column(
        "framework", sa.Enum("nice", "mitre_attack", "nist_csf", "custom", name="competencyframework"), nullable=False
    ),
    sa.Column("category", sa.String(255), nullable=False),
    sa.Column("level", sa.String(50), nullable=False),
    sa.Column("parent_code", sa.String(100)),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
)

competency_assertions = sa.Table(
    "competency_assertions",
    metadata,
    sa.Column("id", GUID(), primary_key=True),
    sa.Column("user_id", GUID(), nullable=False),
    sa.Column("competency_id", GUID(), nullable=False),
    sa.Column(
        "proficiency",
        sa.Enum("novice", "beginner", "intermediate", "advanced", "expert", name="proficiencylevel"),
        nullable=False,
    ),
    sa.Column("evidence_refs", sa.Text(), nullable=False),
    sa.Column("assessed_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("source", sa.String(100), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
)

competency_auto_assessments = sa.Table(
    "competency_auto_assessments",
    metadata,
    sa.Column("id", GUID(), primary_key=True),
    sa.Column("user_id", GUID(), nullable=False),
    sa.Column("exercise_id", GUID()),
    sa.Column("quiz_attempt_id", GUID()),
    sa.Column("competency_mappings", sa.Text(), nullable=False),
    sa.Column("raw_score", sa.Integer(), nullable=False),
    sa.Column("max_score", sa.Integer(), nullable=False),
    sa.Column("assessed_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
)

courses = sa.Table(
    "courses",
    metadata,
    sa.Column("id", GUID(), primary_key=True),
    sa.Column("name", sa.String(255), nullable=False),
    sa.Column("description", sa.Text(), nullable=False),
    sa.Column("version", sa.String(50), nullable=False),
    sa.Column("tenant_id", GUID()),
    sa.Column("is_published", sa.Boolean(), nullable=False),
    sa.Column("difficulty", sa.String(50), nullable=False),
    sa.Column("duration_hours", sa.Integer(), nullable=False),
    sa.Column("tags", sa.Text(), nullable=False),
    sa.Column("nice_work_roles", sa.Text(), nullable=False),
    sa.Column("course_meta", sa.Text(), nullable=False),
    sa.Column("qualification_id", GUID()),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
)

exercises = sa.Table(
    "exercises",
    metadata,
    sa.Column("id", GUID(), primary_key=True),
    sa.Column("name", sa.String(255), nullable=False),
    sa.Column("kind", sa.String(20), nullable=False),
    sa.Column("range_id", GUID(), nullable=False),
    sa.Column("scenario_id", GUID()),
    sa.Column(
        "state", sa.Enum("pending", "running", "paused", "completed", "cancelled", name="exercisestate"), nullable=False
    ),
    sa.Column("tenant_id", GUID()),
    sa.Column("started_at", sa.DateTime(timezone=True)),
    sa.Column("completed_at", sa.DateTime(timezone=True)),
    sa.Column("total_score", sa.Integer(), nullable=False),
    sa.Column("max_score", sa.Integer(), nullable=False),
    sa.Column("deleted_at", sa.DateTime(timezone=True)),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
)

forged_exercises = sa.Table(
    "forged_exercises",
    metadata,
    sa.Column("id", GUID(), primary_key=True),
    sa.Column("exercise_id", GUID(), nullable=False),
    sa.Column("scenario_id", GUID(), nullable=False),
    sa.Column("feed_id", GUID()),
    sa.Column("indicator_ids", sa.Text(), nullable=False),
    sa.Column("scenario_yaml", sa.Text(), nullable=False),
    sa.Column("mitre_techniques", sa.Text(), nullable=False),
    sa.Column("difficulty", sa.String(50), nullable=False),
    sa.Column("model_used", sa.String(255), nullable=False),
    sa.Column("tenant_id", GUID(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
)

golden_images = sa.Table(
    "golden_images",
    metadata,
    sa.Column("id", GUID(), primary_key=True),
    sa.Column("catalogue_id", sa.String(64), nullable=False),
    sa.Column("os_family", sa.String(40), nullable=False),
    sa.Column("version", sa.String(60), nullable=False),
    sa.Column("role", sa.String(160), nullable=False),
    sa.Column("hypervisor", sa.String(20), nullable=False),
    sa.Column("template_name", sa.String(120), nullable=False),
    sa.Column("datastore", sa.String(120), nullable=False),
    sa.Column("os_aliases", sa.Text(), nullable=False),
    sa.Column("sensor_baked", sa.Boolean(), nullable=False),
    sa.Column("enabled", sa.Boolean(), nullable=False),
    sa.Column("build_status", sa.String(20), nullable=False),
    sa.Column("checksum", sa.String(128), nullable=False),
    sa.Column("golden_gb", sa.Integer(), nullable=False),
    sa.Column("notes", sa.Text(), nullable=False),
    sa.Column("tenant_id", GUID()),
    sa.Column("deleted_at", sa.DateTime(timezone=True)),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
)

hypervisor_connections = sa.Table(
    "hypervisor_connections",
    metadata,
    sa.Column("id", GUID(), primary_key=True),
    sa.Column("name", sa.String(255), nullable=False),
    sa.Column("hypervisor_type", sa.String(20), nullable=False),
    sa.Column("host", sa.String(255), nullable=False),
    sa.Column("port", sa.Integer(), nullable=False),
    sa.Column("username", sa.String(255), nullable=False),
    sa.Column("password_encrypted", sa.Text()),
    sa.Column("api_token", sa.Text()),
    sa.Column("verify_ssl", sa.Boolean(), nullable=False),
    sa.Column("is_primary", sa.Boolean(), nullable=False),
    sa.Column("is_active", sa.Boolean(), nullable=False),
    sa.Column("datacenter", sa.String(255)),
    sa.Column("notes", sa.Text()),
    sa.Column("tenant_id", GUID()),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
)

learning_recommendations = sa.Table(
    "learning_recommendations",
    metadata,
    sa.Column("id", GUID(), primary_key=True),
    sa.Column("user_id", GUID(), nullable=False),
    sa.Column("summary", sa.Text(), nullable=False),
    sa.Column("strengths", sa.Text(), nullable=False),
    sa.Column("gaps", sa.Text(), nullable=False),
    sa.Column("recommendations", sa.Text(), nullable=False),
    sa.Column("target_role", sa.String(100)),
    sa.Column("target_role_readiness", sa.Float(), nullable=False),
    sa.Column("next_milestone", sa.Text(), nullable=False),
    sa.Column("model_used", sa.String(255), nullable=False),
    sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
)

objectives = sa.Table(
    "objectives",
    metadata,
    sa.Column("id", GUID(), primary_key=True),
    sa.Column("exercise_id", GUID(), nullable=False),
    sa.Column("ref_id", sa.String(100), nullable=False),
    sa.Column("objective_type", sa.Enum("detection", "response", "deliverable", name="objectivetype"), nullable=False),
    sa.Column("description", sa.Text(), nullable=False),
    sa.Column("validator", sa.String(255), nullable=False),
    sa.Column("validator_params", sa.Text()),
    sa.Column("points", sa.Integer(), nullable=False),
    sa.Column("achieved", sa.Boolean(), nullable=False),
    sa.Column("evidence", sa.Text()),
    sa.Column("achieved_at", sa.DateTime(timezone=True)),
    sa.Column("competency_code", sa.String(50)),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
)

range_snapshots = sa.Table(
    "range_snapshots",
    metadata,
    sa.Column("id", GUID(), primary_key=True),
    sa.Column("range_id", GUID(), nullable=False),
    sa.Column("name", sa.String(255), nullable=False),
    sa.Column("description", sa.Text()),
    sa.Column("snapshot_state", sa.String(20), nullable=False),
    sa.Column("snapshot_data", sa.Text()),
    sa.Column("size_bytes", sa.Integer(), nullable=False),
    sa.Column("range_state_at_snapshot", sa.String(20), nullable=False),
    sa.Column("tenant_id", GUID(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
)

ranges = sa.Table(
    "ranges",
    metadata,
    sa.Column("id", GUID(), primary_key=True),
    sa.Column("name", sa.String(255), nullable=False),
    sa.Column("template_id", GUID(), nullable=False),
    sa.Column(
        "state",
        sa.Enum(
            "created",
            "provisioning",
            "ready",
            "running",
            "stopped",
            "destroying",
            "destroyed",
            "failed",
            name="rangestate",
        ),
        nullable=False,
    ),
    sa.Column("tenant_id", GUID()),
    sa.Column("provisioner_backend", sa.String(50), nullable=False),
    sa.Column("provisioner_output", sa.Text()),
    sa.Column("error_message", sa.Text()),
    sa.Column("diagram_json", sa.JSON()),
    sa.Column("description", sa.Text(), nullable=False),
    sa.Column("deleted_at", sa.DateTime(timezone=True)),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
)

scenarios = sa.Table(
    "scenarios",
    metadata,
    sa.Column("id", GUID(), primary_key=True),
    sa.Column("name", sa.String(255), nullable=False),
    sa.Column("version", sa.String(50), nullable=False),
    sa.Column("yaml", sa.Text(), nullable=False),
    sa.Column("tenant_id", GUID()),
    sa.Column("is_public", sa.Boolean(), nullable=False),
    sa.Column("deleted_at", sa.DateTime(timezone=True)),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
)

templates = sa.Table(
    "templates",
    metadata,
    sa.Column("id", GUID(), primary_key=True),
    sa.Column("name", sa.String(255), nullable=False),
    sa.Column("version", sa.String(50), nullable=False),
    sa.Column("yaml", sa.Text(), nullable=False),
    sa.Column("tenant_id", GUID()),
    sa.Column("is_public", sa.Boolean(), nullable=False),
    sa.Column("deleted_at", sa.DateTime(timezone=True)),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
)

users = sa.Table(
    "users",
    metadata,
    sa.Column("id", GUID(), primary_key=True),
    sa.Column("keycloak_id", sa.String(255), nullable=False, unique=True),
    sa.Column("email", sa.String(320), nullable=False, unique=True),
    sa.Column("display_name", sa.String(255), nullable=False),
    sa.Column(
        "role", sa.Enum("admin", "instructor", "student", "observer", "range_ops", name="userrole"), nullable=False
    ),
    sa.Column("tenant_id", GUID(), nullable=False),
    sa.Column("is_active", sa.Boolean(), nullable=False),
    sa.Column("first_name", sa.String(100)),
    sa.Column("last_name", sa.String(100)),
    sa.Column("rank", sa.String(50)),
    sa.Column("service_branch", sa.String(100)),
    sa.Column("nation_id", GUID()),
    sa.Column("clearance_level", sa.String(50), nullable=False),
    sa.Column("unit", sa.String(255)),
    sa.Column("callsign", sa.String(50)),
    sa.Column("avatar_url", sa.String(512)),
    sa.Column("source", sa.String(20), nullable=False),
    sa.Column("ad_object_guid", sa.String(36), unique=True),
    sa.Column("ad_distinguished_name", sa.String(512)),
    sa.Column("last_synced_at", sa.DateTime(timezone=True)),
    sa.Column("auth_method_preference", sa.String(30)),
    sa.Column("timezone", sa.String(50), nullable=False),
    sa.Column("onboarding_state", sa.String(20), nullable=False),
    sa.Column("onboarded_at", sa.DateTime(timezone=True)),
    sa.Column("onboarding_data", sa.Text(), nullable=False),
    sa.Column("deleted_at", sa.DateTime(timezone=True)),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
)

__all__ = [
    "GUID",
    "after_action_reports",
    "competencies",
    "competency_assertions",
    "competency_auto_assessments",
    "courses",
    "exercises",
    "forged_exercises",
    "golden_images",
    "hypervisor_connections",
    "learning_recommendations",
    "metadata",
    "objectives",
    "range_snapshots",
    "ranges",
    "scenarios",
    "templates",
    "users",
]
