"""initial schema

Revision ID: e49a3ec63fcb
Revises:
Create Date: 2026-04-17 06:58:48.637069

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e49a3ec63fcb'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coalitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=63), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('competencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('framework', sa.Enum('nice', 'mitre_attack', 'custom', name='competencyframework'), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('parent_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('framework', 'code', name='uq_framework_code')
    )
    op.create_index('ix_comp_framework', 'competencies', ['framework'], unique=False)
    op.create_table('nations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('iso_alpha2', sa.String(length=2), nullable=False),
    sa.Column('iso_alpha3', sa.String(length=3), nullable=False),
    sa.Column('flag_emoji', sa.String(length=10), nullable=False),
    sa.Column('is_nato', sa.Boolean(), nullable=False),
    sa.Column('is_fvey', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iso_alpha2'),
    sa.UniqueConstraint('iso_alpha3'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=63), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('ai_backend_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('backend_type', sa.String(length=30), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('max_concurrent', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_zone_policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('zone_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('allowed_methods', sa.Text(), nullable=False),
    sa.Column('require_mfa', sa.Boolean(), nullable=False),
    sa.Column('session_timeout_minutes', sa.Integer(), nullable=False),
    sa.Column('max_failed_attempts', sa.Integer(), nullable=False),
    sa.Column('ip_whitelist', sa.Text(), nullable=True),
    sa.Column('clearance_required', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_name')
    )
    op.create_table('coalition_memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nation_id', sa.String(length=36), nullable=False),
    sa.Column('coalition_id', sa.String(length=36), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['coalition_id'], ['coalitions.id'], ),
    sa.ForeignKeyConstraint(['nation_id'], ['nations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nation_id', 'coalition_id', name='uq_nation_coalition')
    )
    op.create_table('courses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('duration_hours', sa.Integer(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.Column('nice_work_roles', sa.Text(), nullable=False),
    sa.Column('course_meta', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_courses_published', 'courses', ['is_published'], unique=False)
    op.create_index('ix_courses_tenant', 'courses', ['tenant_id'], unique=False)
    op.create_table('detection_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('sigma_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('logsource_category', sa.String(length=100), nullable=True),
    sa.Column('logsource_product', sa.String(length=100), nullable=True),
    sa.Column('logsource_service', sa.String(length=100), nullable=True),
    sa.Column('detection_yaml', sa.Text(), nullable=False),
    sa.Column('mitre_attack_ids', sa.Text(), nullable=True),
    sa.Column('false_positives', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sigma_id')
    )
    op.create_index(op.f('ix_detection_rules_deleted_at'), 'detection_rules', ['deleted_at'], unique=False)
    op.create_index('ix_detection_status', 'detection_rules', ['status'], unique=False)
    op.create_index('ix_detection_tenant', 'detection_rules', ['tenant_id'], unique=False)
    op.create_table('external_platforms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('platform_type', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('auth_type', sa.Enum('lti13', 'oauth2', 'api_key', 'saml', name='integrationauthtype'), nullable=False),
    sa.Column('credentials_encrypted', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('lti_client_id', sa.String(length=255), nullable=True),
    sa.Column('lti_deployment_id', sa.String(length=255), nullable=True),
    sa.Column('lti_issuer', sa.Text(), nullable=True),
    sa.Column('lti_jwks_url', sa.Text(), nullable=True),
    sa.Column('lti_token_url', sa.Text(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_tenant_platform')
    )
    op.create_index('ix_ep_tenant', 'external_platforms', ['tenant_id'], unique=False)
    op.create_table('hypervisor_connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hypervisor_type', sa.String(length=20), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_encrypted', sa.Text(), nullable=True),
    sa.Column('api_token', sa.Text(), nullable=True),
    sa.Column('verify_ssl', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('datacenter', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hv_conn_tenant', 'hypervisor_connections', ['tenant_id'], unique=False)
    op.create_table('kit_definitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('compute_node_count', sa.Integer(), nullable=False),
    sa.Column('storage_appliance_count', sa.Integer(), nullable=False),
    sa.Column('network_device_count', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('learning_paths',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('course_ids', sa.Text(), nullable=False),
    sa.Column('prerequisite_graph', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lp_tenant', 'learning_paths', ['tenant_id'], unique=False)
    op.create_table('network_devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('vendor', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('tor', 'spine', 'leaf', 'firewall', 'router', 'oob', name='networkdevicerole'), nullable=False),
    sa.Column('management_ip', sa.String(length=255), nullable=False),
    sa.Column('firmware_version', sa.String(length=100), nullable=True),
    sa.Column('port_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizational_units',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('ou_type', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('dn_path', sa.String(length=1024), nullable=True),
    sa.Column('nation_id', sa.String(length=36), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['nation_id'], ['nations.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['organizational_units.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('yaml', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_deleted_at'), 'scenarios', ['deleted_at'], unique=False)
    op.create_index('ix_scenarios_tenant', 'scenarios', ['tenant_id'], unique=False)
    op.create_table('storage_appliances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('vendor', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('management_ip', sa.String(length=255), nullable=False),
    sa.Column('protocol', sa.Enum('nfs', 'iscsi', 'fc', 'nvme_of', 'smb', name='storageprotocol'), nullable=False),
    sa.Column('raw_capacity_tb', sa.Float(), nullable=False),
    sa.Column('usable_capacity_tb', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('yaml', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_deleted_at'), 'templates', ['deleted_at'], unique=False)
    op.create_index('ix_templates_tenant', 'templates', ['tenant_id'], unique=False)
    op.create_table('threat_intel_feeds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('feed_type', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('collection_id', sa.String(length=255), nullable=True),
    sa.Column('api_key_ref', sa.String(length=255), nullable=True),
    sa.Column('poll_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_poll_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_poll_status', sa.String(length=50), nullable=True),
    sa.Column('indicator_count', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_intel_feeds_deleted_at'), 'threat_intel_feeds', ['deleted_at'], unique=False)
    op.create_index('ix_ti_feed_tenant', 'threat_intel_feeds', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('keycloak_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'instructor', 'student', 'observer', 'range_ops', name='userrole'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('rank', sa.String(length=50), nullable=True),
    sa.Column('service_branch', sa.String(length=100), nullable=True),
    sa.Column('nation_id', sa.String(length=36), nullable=True),
    sa.Column('clearance_level', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=255), nullable=True),
    sa.Column('callsign', sa.String(length=50), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('ad_object_guid', sa.String(length=36), nullable=True),
    sa.Column('ad_distinguished_name', sa.String(length=512), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auth_method_preference', sa.String(length=30), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['nation_id'], ['nations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ad_object_guid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('keycloak_id')
    )
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index('ix_users_email_lower', 'users', ['email'], unique=False)
    op.create_index('ix_users_tenant_role', 'users', ['tenant_id', 'role'], unique=False)
    op.create_table('ai_fleet_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('backend_id', sa.String(length=36), nullable=False),
    sa.Column('node_name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('gpu_model', sa.String(length=100), nullable=True),
    sa.Column('gpu_vram_gb', sa.Float(), nullable=True),
    sa.Column('loaded_models', sa.Text(), nullable=True),
    sa.Column('current_requests', sa.Integer(), nullable=False),
    sa.Column('max_requests', sa.Integer(), nullable=False),
    sa.Column('last_health_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['backend_id'], ['ai_backend_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_fleet_backend', 'ai_fleet_nodes', ['backend_id'], unique=False)
    op.create_table('ai_model_routes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model_pattern', sa.String(length=255), nullable=False),
    sa.Column('backend_id', sa.String(length=36), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['backend_id'], ['ai_backend_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_audit_tenant_ts', 'audit_logs', ['tenant_id', 'timestamp'], unique=False)
    op.create_table('certifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('cert_name', sa.String(length=255), nullable=False),
    sa.Column('issuer', sa.String(length=255), nullable=False),
    sa.Column('credential_id', sa.String(length=255), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('nice_work_roles', sa.Text(), nullable=False),
    sa.Column('dod_8140_category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_certs_user', 'certifications', ['user_id'], unique=False)
    op.create_index('ix_certs_user_issuer', 'certifications', ['user_id', 'issuer'], unique=False)
    op.create_table('competency_assertions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('competency_id', sa.String(length=36), nullable=False),
    sa.Column('proficiency', sa.Enum('novice', 'beginner', 'intermediate', 'advanced', 'expert', name='proficiencylevel'), nullable=False),
    sa.Column('evidence_refs', sa.Text(), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ca_competency', 'competency_assertions', ['competency_id'], unique=False)
    op.create_index('ix_ca_user', 'competency_assertions', ['user_id'], unique=False)
    op.create_index('ix_ca_user_comp', 'competency_assertions', ['user_id', 'competency_id'], unique=False)
    op.create_table('course_modules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('content_type', sa.Enum('scenario', 'external_lti', 'reading', 'quiz', 'video', name='modulecontenttype'), nullable=False),
    sa.Column('content_ref', sa.Text(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('pass_threshold', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_modules_course_ordinal', 'course_modules', ['course_id', 'ordinal'], unique=False)
    op.create_table('enrollments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('enrolled', 'in_progress', 'completed', 'withdrawn', 'failed', name='enrollmentstatus'), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_grade', sa.String(length=10), nullable=True),
    sa.Column('final_score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id', name='uq_user_course')
    )
    op.create_index('ix_enroll_course_status', 'enrollments', ['course_id', 'status'], unique=False)
    op.create_index('ix_enroll_tenant', 'enrollments', ['tenant_id'], unique=False)
    op.create_index('ix_enroll_user', 'enrollments', ['user_id'], unique=False)
    op.create_table('external_activities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('platform_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('external_ref', sa.String(length=500), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=False),
    sa.Column('xapi_statement_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['external_platforms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ea_platform', 'external_activities', ['platform_id'], unique=False)
    op.create_index('ix_ea_user', 'external_activities', ['user_id'], unique=False)
    op.create_index('ix_ea_user_platform', 'external_activities', ['user_id', 'platform_id'], unique=False)
    op.create_table('hypervisor_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('node_name', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cpu_total', sa.Integer(), nullable=True),
    sa.Column('cpu_used', sa.Float(), nullable=True),
    sa.Column('memory_total_gb', sa.Float(), nullable=True),
    sa.Column('memory_used_gb', sa.Float(), nullable=True),
    sa.Column('storage_total_gb', sa.Float(), nullable=True),
    sa.Column('storage_used_gb', sa.Float(), nullable=True),
    sa.Column('vm_count', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['hypervisor_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hv_node_conn', 'hypervisor_nodes', ['connection_id'], unique=False)
    op.create_table('hypervisor_pools',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('pool_name', sa.String(length=255), nullable=False),
    sa.Column('pool_type', sa.String(length=30), nullable=False),
    sa.Column('total_capacity_gb', sa.Float(), nullable=True),
    sa.Column('used_capacity_gb', sa.Float(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['hypervisor_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hv_pool_conn', 'hypervisor_pools', ['connection_id'], unique=False)
    op.create_table('learning_recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('strengths', sa.Text(), nullable=False),
    sa.Column('gaps', sa.Text(), nullable=False),
    sa.Column('recommendations', sa.Text(), nullable=False),
    sa.Column('target_role', sa.String(length=100), nullable=True),
    sa.Column('target_role_readiness', sa.Float(), nullable=False),
    sa.Column('next_milestone', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(length=255), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_learn_rec_user', 'learning_recommendations', ['user_id'], unique=False)
    op.create_table('lti_nonces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nonce', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('platform_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['external_platforms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nonce')
    )
    op.create_index('ix_lti_nonce_exp', 'lti_nonces', ['expires_at'], unique=False)
    op.create_table('ranges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.Enum('created', 'provisioning', 'ready', 'running', 'stopped', 'destroying', 'destroyed', 'failed', name='rangestate'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('provisioner_backend', sa.String(length=50), nullable=False),
    sa.Column('provisioner_output', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ranges_deleted_at'), 'ranges', ['deleted_at'], unique=False)
    op.create_index('ix_ranges_template', 'ranges', ['template_id'], unique=False)
    op.create_index('ix_ranges_tenant_state', 'ranges', ['tenant_id', 'state'], unique=False)
    op.create_table('security_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('group_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ou_id', sa.String(length=36), nullable=True),
    sa.Column('ad_object_guid', sa.String(length=36), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ou_id'], ['organizational_units.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sg_tenant', 'security_groups', ['tenant_id'], unique=False)
    op.create_table('storage_volumes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('appliance_id', sa.String(length=36), nullable=False),
    sa.Column('volume_name', sa.String(length=255), nullable=False),
    sa.Column('size_gb', sa.Float(), nullable=False),
    sa.Column('used_gb', sa.Float(), nullable=False),
    sa.Column('protocol', sa.Enum('nfs', 'iscsi', 'fc', 'nvme_of', 'smb', name='storageprotocol'), nullable=False),
    sa.Column('mount_path', sa.String(length=512), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['appliance_id'], ['storage_appliances.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threat_indicators',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('feed_id', sa.String(length=36), nullable=False),
    sa.Column('stix_id', sa.String(length=255), nullable=True),
    sa.Column('indicator_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=2048), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('kill_chain_phases', sa.Text(), nullable=True),
    sa.Column('mitre_attack_ids', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['threat_intel_feeds.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stix_id')
    )
    op.create_index('ix_ti_indicator_feed', 'threat_indicators', ['feed_id'], unique=False)
    op.create_index('ix_ti_indicator_tenant', 'threat_indicators', ['tenant_id'], unique=False)
    op.create_index('ix_ti_indicator_type_value', 'threat_indicators', ['indicator_type', 'value'], unique=False)
    op.create_table('exercises',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('range_id', sa.String(length=36), nullable=False),
    sa.Column('scenario_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.Enum('pending', 'running', 'paused', 'completed', 'cancelled', name='exercisestate'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['range_id'], ['ranges.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_deleted_at'), 'exercises', ['deleted_at'], unique=False)
    op.create_index('ix_exercises_range', 'exercises', ['range_id'], unique=False)
    op.create_index('ix_exercises_scenario', 'exercises', ['scenario_id'], unique=False)
    op.create_index('ix_exercises_tenant_state', 'exercises', ['tenant_id', 'state'], unique=False)
    op.create_table('module_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enrollment_id', sa.String(length=36), nullable=False),
    sa.Column('module_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'completed', 'skipped', name='moduleprogressstatus'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['course_modules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'module_id', name='uq_enroll_module')
    )
    op.create_index('ix_mp_enrollment', 'module_progress', ['enrollment_id'], unique=False)
    op.create_table('range_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('range_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('snapshot_state', sa.String(length=20), nullable=False),
    sa.Column('snapshot_data', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('range_state_at_snapshot', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['range_id'], ['ranges.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_snapshot_range', 'range_snapshots', ['range_id'], unique=False)
    op.create_index('ix_snapshot_tenant', 'range_snapshots', ['tenant_id'], unique=False)
    op.create_table('scheduled_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('state', sa.Enum('draft', 'scheduled', 'active', 'completed', 'cancelled', name='eventstate'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('range_id', sa.String(length=36), nullable=True),
    sa.Column('template_id', sa.String(length=36), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vm_count', sa.Integer(), nullable=False),
    sa.Column('vcpu_total', sa.Integer(), nullable=False),
    sa.Column('ram_mb_total', sa.Integer(), nullable=False),
    sa.Column('disk_gb_total', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['range_id'], ['ranges.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_state', 'scheduled_events', ['state'], unique=False)
    op.create_index('ix_event_tenant_start', 'scheduled_events', ['tenant_id', 'start_time'], unique=False)
    op.create_table('security_group_memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['security_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'group_id', name='uq_user_secgroup')
    )
    op.create_table('after_action_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('exercise_id', sa.String(length=36), nullable=False),
    sa.Column('report_json', sa.Text(), nullable=False),
    sa.Column('report_html', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exercise_id')
    )
    op.create_table('analyst_annotations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('exercise_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('user_display_name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('annotation_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('related_event_id', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_annotation_exercise', 'analyst_annotations', ['exercise_id'], unique=False)
    op.create_index('ix_annotation_user', 'analyst_annotations', ['user_id'], unique=False)
    op.create_table('competency_auto_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('exercise_id', sa.String(length=36), nullable=False),
    sa.Column('competency_mappings', sa.Text(), nullable=False),
    sa.Column('raw_score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auto_assess_exercise', 'competency_auto_assessments', ['exercise_id'], unique=False)
    op.create_index('ix_auto_assess_user', 'competency_auto_assessments', ['user_id'], unique=False)
    op.create_table('forged_exercises',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('exercise_id', sa.String(length=36), nullable=False),
    sa.Column('scenario_id', sa.String(length=36), nullable=False),
    sa.Column('feed_id', sa.String(length=36), nullable=True),
    sa.Column('indicator_ids', sa.Text(), nullable=False),
    sa.Column('scenario_yaml', sa.Text(), nullable=False),
    sa.Column('mitre_techniques', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('model_used', sa.String(length=255), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['feed_id'], ['threat_intel_feeds.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_forged_feed', 'forged_exercises', ['feed_id'], unique=False)
    op.create_index('ix_forged_tenant', 'forged_exercises', ['tenant_id'], unique=False)
    op.create_table('objectives',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('exercise_id', sa.String(length=36), nullable=False),
    sa.Column('ref_id', sa.String(length=100), nullable=False),
    sa.Column('objective_type', sa.Enum('detection', 'response', 'deliverable', name='objectivetype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('validator', sa.String(length=255), nullable=False),
    sa.Column('validator_params', sa.Text(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('achieved', sa.Boolean(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_objectives_exercise', 'objectives', ['exercise_id'], unique=False)
    op.create_index('ix_objectives_exercise_achieved', 'objectives', ['exercise_id', 'achieved'], unique=False)
    op.create_table('shared_commands',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('exercise_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('user_display_name', sa.String(length=255), nullable=False),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('host_tag', sa.String(length=100), nullable=False),
    sa.Column('shared_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shared_cmd_exercise', 'shared_commands', ['exercise_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('team_type', sa.String(length=20), nullable=True),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('ou_id', sa.String(length=36), nullable=True),
    sa.Column('nation_id', sa.String(length=36), nullable=True),
    sa.Column('max_members', sa.Integer(), nullable=True),
    sa.Column('is_persistent', sa.Boolean(), nullable=False),
    sa.Column('exercise_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['nation_id'], ['nations.id'], ),
    sa.ForeignKeyConstraint(['ou_id'], ['organizational_units.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_teams_tenant', 'teams', ['tenant_id'], unique=False)
    op.create_table('team_memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'team_id', name='uq_user_team')
    )
    op.create_index('ix_tm_team', 'team_memberships', ['team_id'], unique=False)
    op.create_index('ix_tm_user', 'team_memberships', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tm_user', table_name='team_memberships')
    op.drop_index('ix_tm_team', table_name='team_memberships')
    op.drop_table('team_memberships')
    op.drop_index('ix_teams_tenant', table_name='teams')
    op.drop_table('teams')
    op.drop_index('ix_shared_cmd_exercise', table_name='shared_commands')
    op.drop_table('shared_commands')
    op.drop_index('ix_objectives_exercise_achieved', table_name='objectives')
    op.drop_index('ix_objectives_exercise', table_name='objectives')
    op.drop_table('objectives')
    op.drop_index('ix_forged_tenant', table_name='forged_exercises')
    op.drop_index('ix_forged_feed', table_name='forged_exercises')
    op.drop_table('forged_exercises')
    op.drop_index('ix_auto_assess_user', table_name='competency_auto_assessments')
    op.drop_index('ix_auto_assess_exercise', table_name='competency_auto_assessments')
    op.drop_table('competency_auto_assessments')
    op.drop_index('ix_annotation_user', table_name='analyst_annotations')
    op.drop_index('ix_annotation_exercise', table_name='analyst_annotations')
    op.drop_table('analyst_annotations')
    op.drop_table('after_action_reports')
    op.drop_table('security_group_memberships')
    op.drop_index('ix_event_tenant_start', table_name='scheduled_events')
    op.drop_index('ix_event_state', table_name='scheduled_events')
    op.drop_table('scheduled_events')
    op.drop_index('ix_snapshot_tenant', table_name='range_snapshots')
    op.drop_index('ix_snapshot_range', table_name='range_snapshots')
    op.drop_table('range_snapshots')
    op.drop_index('ix_mp_enrollment', table_name='module_progress')
    op.drop_table('module_progress')
    op.drop_index('ix_exercises_tenant_state', table_name='exercises')
    op.drop_index('ix_exercises_scenario', table_name='exercises')
    op.drop_index('ix_exercises_range', table_name='exercises')
    op.drop_index(op.f('ix_exercises_deleted_at'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index('ix_ti_indicator_type_value', table_name='threat_indicators')
    op.drop_index('ix_ti_indicator_tenant', table_name='threat_indicators')
    op.drop_index('ix_ti_indicator_feed', table_name='threat_indicators')
    op.drop_table('threat_indicators')
    op.drop_table('storage_volumes')
    op.drop_index('ix_sg_tenant', table_name='security_groups')
    op.drop_table('security_groups')
    op.drop_index('ix_ranges_tenant_state', table_name='ranges')
    op.drop_index('ix_ranges_template', table_name='ranges')
    op.drop_index(op.f('ix_ranges_deleted_at'), table_name='ranges')
    op.drop_table('ranges')
    op.drop_index('ix_lti_nonce_exp', table_name='lti_nonces')
    op.drop_table('lti_nonces')
    op.drop_index('ix_learn_rec_user', table_name='learning_recommendations')
    op.drop_table('learning_recommendations')
    op.drop_index('ix_hv_pool_conn', table_name='hypervisor_pools')
    op.drop_table('hypervisor_pools')
    op.drop_index('ix_hv_node_conn', table_name='hypervisor_nodes')
    op.drop_table('hypervisor_nodes')
    op.drop_index('ix_ea_user_platform', table_name='external_activities')
    op.drop_index('ix_ea_user', table_name='external_activities')
    op.drop_index('ix_ea_platform', table_name='external_activities')
    op.drop_table('external_activities')
    op.drop_index('ix_enroll_user', table_name='enrollments')
    op.drop_index('ix_enroll_tenant', table_name='enrollments')
    op.drop_index('ix_enroll_course_status', table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index('ix_modules_course_ordinal', table_name='course_modules')
    op.drop_table('course_modules')
    op.drop_index('ix_ca_user_comp', table_name='competency_assertions')
    op.drop_index('ix_ca_user', table_name='competency_assertions')
    op.drop_index('ix_ca_competency', table_name='competency_assertions')
    op.drop_table('competency_assertions')
    op.drop_index('ix_certs_user_issuer', table_name='certifications')
    op.drop_index('ix_certs_user', table_name='certifications')
    op.drop_table('certifications')
    op.drop_index('ix_audit_tenant_ts', table_name='audit_logs')
    op.drop_index('ix_audit_resource', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('ai_model_routes')
    op.drop_index('ix_ai_fleet_backend', table_name='ai_fleet_nodes')
    op.drop_table('ai_fleet_nodes')
    op.drop_index('ix_users_tenant_role', table_name='users')
    op.drop_index('ix_users_email_lower', table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_ti_feed_tenant', table_name='threat_intel_feeds')
    op.drop_index(op.f('ix_threat_intel_feeds_deleted_at'), table_name='threat_intel_feeds')
    op.drop_table('threat_intel_feeds')
    op.drop_index('ix_templates_tenant', table_name='templates')
    op.drop_index(op.f('ix_templates_deleted_at'), table_name='templates')
    op.drop_table('templates')
    op.drop_table('storage_appliances')
    op.drop_index('ix_scenarios_tenant', table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_deleted_at'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_table('organizational_units')
    op.drop_table('network_devices')
    op.drop_index('ix_lp_tenant', table_name='learning_paths')
    op.drop_table('learning_paths')
    op.drop_table('kit_definitions')
    op.drop_index('ix_hv_conn_tenant', table_name='hypervisor_connections')
    op.drop_table('hypervisor_connections')
    op.drop_index('ix_ep_tenant', table_name='external_platforms')
    op.drop_table('external_platforms')
    op.drop_index('ix_detection_tenant', table_name='detection_rules')
    op.drop_index('ix_detection_status', table_name='detection_rules')
    op.drop_index(op.f('ix_detection_rules_deleted_at'), table_name='detection_rules')
    op.drop_table('detection_rules')
    op.drop_index('ix_courses_tenant', table_name='courses')
    op.drop_index('ix_courses_published', table_name='courses')
    op.drop_table('courses')
    op.drop_table('coalition_memberships')
    op.drop_table('auth_zone_policies')
    op.drop_table('ai_backend_configs')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_table('nations')
    op.drop_index('ix_comp_framework', table_name='competencies')
    op.drop_table('competencies')
    op.drop_table('coalitions')
    # ### end Alembic commands ###
