{{- if .Values.workerProvision.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "truenorth-range.fullname" . }}-worker-provision
  labels:
    {{- include "truenorth-range.componentLabels" (dict "context" . "component" "worker-provision") | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "truenorth-range.componentSelectorLabels" (dict "context" . "component" "worker-provision") | nindent 6 }}
{{- end }}
---
{{- if .Values.workerScenario.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "truenorth-range.fullname" . }}-worker-scenario
  labels:
    {{- include "truenorth-range.componentLabels" (dict "context" . "component" "worker-scenario") | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "truenorth-range.componentSelectorLabels" (dict "context" . "component" "worker-scenario") | nindent 6 }}
{{- end }}
---
{{- if .Values.workerTelemetry.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "truenorth-range.fullname" . }}-worker-telemetry
  labels:
    {{- include "truenorth-range.componentLabels" (dict "context" . "component" "worker-telemetry") | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "truenorth-range.componentSelectorLabels" (dict "context" . "component" "worker-telemetry") | nindent 6 }}
{{- end }}