apiVersion: v1
kind: Secret
metadata:
  name: {{ include "truenorth-range.fullname" . }}-secret
  labels:
    {{- include "truenorth-range.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_PASSWORD: {{ .Values.secrets.databasePassword | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | b64enc | quote }}
  MINIO_ACCESS_KEY: {{ .Values.secrets.minioAccessKey | b64enc | quote }}
  MINIO_SECRET_KEY: {{ .Values.secrets.minioSecretKey | b64enc | quote }}
  API_SECRET_KEY: {{ .Values.secrets.apiSecretKey | b64enc | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.secrets.keycloakAdminPassword | b64enc | quote }}