{{- if .Values.aiOrchestrator.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "truenorth-range.fullname" . }}-ai-orchestrator
  labels:
    {{- include "truenorth-range.componentLabels" (dict "context" . "component" "ai-orchestrator") | nindent 4 }}
spec:
  type: {{ .Values.aiOrchestrator.service.type }}
  ports:
    - port: {{ .Values.aiOrchestrator.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "truenorth-range.componentSelectorLabels" (dict "context" . "component" "ai-orchestrator") | nindent 4 }}
{{- end }}