#!/usr/bin/env bash
# =============================================================================
# TrueNorth Range — backup/restore drill
# =============================================================================
# Proves backup.sh + restore.sh against the REAL production compose file, in a
# disposable compose project that shares nothing with a running stack:
#
#   1. bring up postgres + minio from compose.prod.yml under a unique project name,
#      with an override that swaps the bind-mounted data volumes for throwaway
#      named volumes, renames the fixed networks and drops the production memory
#      sizing (nothing else is changed);
#   2. seed: rows in the app, keycloak and lrs databases (each owned by its own
#      role, as in production) and objects in three buckets (one empty);
#   3. backup.sh, with an escrow key generated for the drill;
#   4. wipe: `down -v` (volumes deleted), bring the services back empty;
#   5. restore.sh;
#   6. verify: per-database, per-table row counts and owners, bucket list and
#      object count are identical before and after; the escrow decrypts back to
#      the exact env file; a second backup of the restored stack succeeds; a
#      backup pointed at a missing env file exits non-zero with an ALERT;
#   7. tear down (always, via trap).
#
# Usage: drill.sh             DRILL_PROJECT=<name> to choose the project name,
#                             DRILL_REPORT=<file> to also write the summary there,
#                             DRILL_KEEP=1 to leave the project up for inspection.
# Needs: docker with compose v2.24+ (for !reset), openssl 3.
# =============================================================================
set -euo pipefail
IFS=$'\n\t'
umask 077

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "${HERE}/../.." && pwd)"
DRILL_PROJECT="${DRILL_PROJECT:-tn-drill-$(date +%s)-$$}"
DRILL_REPORT="${DRILL_REPORT:-}"
DRILL_KEEP="${DRILL_KEEP:-0}"
OPENSSL="${OPENSSL:-openssl}"

case "${DRILL_PROJECT}" in
    truenorth|docker|tn-r0-pg|"") echo "refusing to drill against project '${DRILL_PROJECT}'" >&2; exit 2 ;;
esac
if [[ -n "$(docker compose -p "${DRILL_PROJECT}" ps -aq 2>/dev/null)" ]]; then
    echo "compose project '${DRILL_PROJECT}' already has containers; pick another DRILL_PROJECT" >&2
    exit 2
fi

WORK="$(mktemp -d "${TMPDIR:-/tmp}/tn-drill.XXXXXX")"
WORK="$(cd "${WORK}" && pwd -P)"
mkdir -p "${WORK}/backups" "${WORK}/seed"

export COMPOSE_PROJECT_NAME="${DRILL_PROJECT}"
export COMPOSE_FILE="${ROOT}/infra/platform/docker/compose.prod.yml:${WORK}/drill.override.yml"
export ENV_FILE="${WORK}/env.production"
export BACKUP_DIR="${WORK}/backups"
export BACKUP_ESCROW_PUBKEY="${WORK}/escrow.pub"
export OPENSSL

# shellcheck source=scripts/backup/lib.sh
source "${HERE}/lib.sh"
TN_LOG_TAG="truenorth-drill"

teardown() {
    local rc=$?
    if [[ "${DRILL_KEEP}" == "1" ]]; then
        log "INFO" "DRILL_KEEP=1: leaving project ${DRILL_PROJECT} and ${WORK}"
    else
        log "INFO" "Tearing down ${DRILL_PROJECT}"
        docker compose -p "${DRILL_PROJECT}" down -v --remove-orphans >/dev/null 2>&1 || true
        rm -rf "${WORK}"
    fi
    if (( rc != 0 )); then
        echo "DRILL FAILED (exit ${rc})" >&2
    fi
}
trap teardown EXIT

rand() { "${OPENSSL}" rand -hex "${1:-16}"; }

# ── Disposable environment ───────────────────────────────────────────────────
cat >"${ENV_FILE}" <<EOF
# Generated by scripts/backup/drill.sh for project ${DRILL_PROJECT}. Throwaway.
DOMAIN=drill.invalid
POSTGRES_USER=drill_admin
POSTGRES_PASSWORD=$(rand)
POSTGRES_DB=drill_app
KEYCLOAK_DB=keycloak
KEYCLOAK_DB_USER=keycloak
KEYCLOAK_DB_PASSWORD=$(rand)
LRS_DB=lrs
LRS_DB_USER=lrs
LRS_DB_PASSWORD=$(rand)
MINIO_ACCESS_KEY=drill$(rand 4)
MINIO_SECRET_KEY=$(rand)
REDIS_PASSWORD=$(rand)
TN_SECRETS_KEY=$(rand 32),$(rand 32)
# Unused by postgres/minio; set only so compose does not warn about them.
FLOWER_USER=x
FLOWER_PASSWORD=x
LRS_ADMIN_USER=x
LRS_ADMIN_PASSWORD=x
LRS_API_KEY=x
LRS_API_SECRET=x
LRS_AUTH=x
GRAFANA_ADMIN_PASSWORD=x
KEYCLOAK_ADMIN_USER=x
KEYCLOAK_ADMIN_PASSWORD=x
LDAP_SERVER=x
LDAP_BASE_DN=x
KEYCLOAK_LDAP_COMPONENT_ID=x
REGISTRATION_ALLOWED_GROUPS=x
REGISTRATION_GROUP_ROLE_MAP={}
REGISTRATION_DEFAULT_PROGRESSION=x
JWT_SECRET=x
CSRF_SECRET=x
EOF

cat >"${WORK}/drill.override.yml" <<EOF
# Drill-only override: isolation, not behaviour. See drill.sh.
services:
  postgres:
    command: ["postgres", "-c", "shared_buffers=128MB", "-c", "max_connections=100"]
    deploy: !reset {}
  minio:
    deploy: !reset {}
volumes:
  pg-data:
    driver_opts: !reset {}
  minio-data:
    driver_opts: !reset {}
networks:
  tn-backend:
    name: ${DRILL_PROJECT}-backend
  tn-frontend:
    name: ${DRILL_PROJECT}-frontend
  tn-monitoring:
    name: ${DRILL_PROJECT}-monitoring
EOF

"${OPENSSL}" genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:3072 -out "${WORK}/escrow.key" 2>/dev/null
"${OPENSSL}" pkey -in "${WORK}/escrow.key" -pubout -out "${WORK}/escrow.pub"

compose_init
PG_USER="$(env_get POSTGRES_USER)"
PG_DB="$(env_get POSTGRES_DB)"

start_stack() {
    dc up -d --quiet-pull postgres minio >/dev/null
    # pg_isready answers during initdb's temporary server; wait for the real one.
    local i
    for i in $(seq 1 90); do
        if dc logs postgres 2>/dev/null | grep -q 'PostgreSQL init process complete' \
           && dc exec -T postgres pg_isready -q -U "${PG_USER}" -d "${PG_DB}" 2>/dev/null; then
            break
        fi
        sleep 2
    done
    dc exec -T postgres pg_isready -q -U "${PG_USER}" -d "${PG_DB}" || die "postgres did not come up"
    for i in $(seq 1 60); do
        if mc_run "${WORK}/seed" ls tn >/dev/null 2>&1; then return 0; fi
        sleep 2
    done
    die "minio did not come up"
}

psql_as() { # psql_as <role> <db> <sql>
    dc exec -T postgres psql -v ON_ERROR_STOP=1 -q -U "$1" -d "$2" -c "$3"
}

# Every user table in every database: "<db> <schema.table> <owner> <rows>"; then
# the bucket list and the object count.
snapshot() {
    local db
    while IFS= read -r db; do
        [[ -n "$db" ]] || continue
        # </dev/null: `exec -T` would otherwise swallow the rest of the db list.
        dc exec -T postgres psql -U "${PG_USER}" -d "$db" -v ON_ERROR_STOP=1 -At -F ' ' -c "
            select current_database(), schemaname||'.'||tablename, tableowner,
                   (xpath('/row/c/text()', query_to_xml(
                       format('select count(*) as c from %I.%I', schemaname, tablename),
                       false, true, '')))[1]::text
            from pg_tables
            where schemaname not in ('pg_catalog', 'information_schema')
            order by 2" </dev/null
    done < <(dc exec -T postgres psql -U "${PG_USER}" -d "${PG_DB}" -Atc \
        "select datname from pg_database where not datistemplate order by 1" | tr -d '\r')
    printf 'minio buckets %s\n' "$(mc_run "${WORK}/seed" ls tn | awk '{print $NF}' | tr -d '/' | sort | paste -sd, -)"
    printf 'minio objects %s\n' "$(mc_run "${WORK}/seed" ls --recursive tn | grep -c . || true)"
}

# ── 1. Up ────────────────────────────────────────────────────────────────────
log "INFO" "Drill project ${DRILL_PROJECT} (work dir ${WORK})"
start_stack

# ── 2. Seed ──────────────────────────────────────────────────────────────────
log "INFO" "Seeding..."
psql_as "${PG_USER}" "${PG_DB}" "
    create table ranges (id serial primary key, name text not null, created timestamptz default now());
    insert into ranges (name) select 'range-' || g from generate_series(1, 1000) g;
    create table enrollments (id bigserial primary key, range_id int references ranges(id), student text);
    insert into enrollments (range_id, student) select 1 + (g % 1000), 'student-' || g from generate_series(1, 2500) g;"
# Companion databases, written by their own roles exactly as Keycloak and the LRS do.
dc exec -T postgres psql -v ON_ERROR_STOP=1 -q -U "${PG_USER}" -d keycloak -c "
    set role keycloak;
    create table user_entity (id text primary key, username text);
    insert into user_entity select 'u' || g, 'user' || g from generate_series(1, 137) g;"
dc exec -T postgres psql -v ON_ERROR_STOP=1 -q -U "${PG_USER}" -d lrs -c "
    set role lrs;
    create table xapi_statement (id uuid primary key default gen_random_uuid(), payload jsonb);
    insert into xapi_statement (payload) select jsonb_build_object('n', g) from generate_series(1, 420) g;"

mkdir -p "${WORK}/seed/truenorth-artifacts/aar" "${WORK}/seed/truenorth-uploads"
for i in $(seq 1 23); do rand 64 >"${WORK}/seed/truenorth-artifacts/aar/report-${i}.json"; done
for i in $(seq 1 9); do rand 256 >"${WORK}/seed/truenorth-uploads/file-${i}.bin"; done
for b in truenorth-artifacts truenorth-uploads truenorth-empty; do
    mc_run "${WORK}/seed" mb --ignore-existing "tn/${b}" >/dev/null
done
mc_run "${WORK}/seed" mirror --quiet /backup/truenorth-artifacts tn/truenorth-artifacts >/dev/null
mc_run "${WORK}/seed" mirror --quiet /backup/truenorth-uploads tn/truenorth-uploads >/dev/null

snapshot >"${WORK}/before.txt"

# ── 3. Backup ────────────────────────────────────────────────────────────────
log "INFO" "Backup..."
"${HERE}/backup.sh"
BACKUP="$(find "${BACKUP_DIR}" -mindepth 1 -maxdepth 1 -type d -name 'truenorth-backup-*' | sort | tail -n 1)"
[[ -n "${BACKUP}" ]] || die "backup.sh produced no backup directory"

# ── 4. Wipe ──────────────────────────────────────────────────────────────────
log "INFO" "Wipe (down -v) and bring up empty..."
dc down -v >/dev/null 2>&1
start_stack
snapshot >"${WORK}/wiped.txt"
if cmp -s "${WORK}/before.txt" "${WORK}/wiped.txt"; then
    die "wipe did not change anything; the drill would prove nothing"
fi

# ── 5. Restore ───────────────────────────────────────────────────────────────
log "INFO" "Restore..."
"${HERE}/restore.sh" "${BACKUP}" --force --no-restart

# ── 6. Verify ────────────────────────────────────────────────────────────────
snapshot >"${WORK}/after.txt"
if ! diff -u "${WORK}/before.txt" "${WORK}/after.txt" >&2; then
    die "restored state differs from the seeded state"
fi
"${HERE}/escrow-open.sh" "${BACKUP}" "${WORK}/escrow.key" "${WORK}/env.recovered" 2>/dev/null
cmp -s "${ENV_FILE}" "${WORK}/env.recovered" || die "escrow did not decrypt to the original env file"
grep -q '^TN_SECRETS_KEY=' "${WORK}/env.recovered" || die "escrowed env has no TN_SECRETS_KEY"
if grep -rqs -- "$(env_get TN_SECRETS_KEY | cut -d, -f1)" "${BACKUP}"; then
    die "TN_SECRETS_KEY found in plain text inside the backup"
fi

sleep 1  # distinct timestamp for the second backup
"${HERE}/backup.sh" >/dev/null
[[ "$(find "${BACKUP_DIR}" -mindepth 1 -maxdepth 1 -type d -name 'truenorth-backup-*' | grep -c .)" == 2 ]] \
    || die "second backup (of the restored stack) did not produce a backup"

set +e
ENV_FILE="${WORK}/missing.env" "${HERE}/backup.sh" >/dev/null 2>"${WORK}/fail.err"
fail_rc=$?
set -e
(( fail_rc != 0 )) || die "backup.sh with a missing env file exited 0"
grep -q 'ALERT\|ERROR' "${WORK}/fail.err" || die "backup.sh failure produced no alert on stderr"

# ── Report ───────────────────────────────────────────────────────────────────
{
    echo "TrueNorth backup drill — PASS"
    echo "project: ${DRILL_PROJECT}   backup: $(basename "${BACKUP}")"
    echo "databases: $(sed -n 's/.*"databases": \[\(.*\)\]}.*/\1/p' "${BACKUP}/manifest.json" | grep -o '"name":"[^"]*"' | cut -d'"' -f4 | paste -sd, -)"
    echo "state before backup == state after restore:"
    sed 's/^/  /' "${WORK}/after.txt"
    echo "escrow: decrypts to the original env file; TN_SECRETS_KEY not in plain text"
    echo "second backup after restore: ok; failure path: exit ${fail_rc} with alert"
} | tee "${WORK}/report.txt"
if [[ -n "${DRILL_REPORT}" ]]; then cp "${WORK}/report.txt" "${DRILL_REPORT}"; fi
