#!/usr/bin/env python3
"""Helm values that pin every TrueNorth image to a release's digests.

Reads a release's ``release-manifest.json`` (docs/release.md, "Installing by digest")
and prints the chart's ``images`` block plus ``version``, so an install runs exactly the
images that release scanned::

    gh release download v1.2.3 -R mblanke/TrueNorth -p release-manifest.json -p SHA256SUMS
    python3 infra/k8s/scripts/values_from_manifest.py release-manifest.json \\
        --sums SHA256SUMS > images-v1.2.3.yaml
    helm upgrade --install tn infra/k8s/helm/truenorth-range -f my-values.yaml \\
        -f images-v1.2.3.yaml

Standard library only. Exits non-zero, writing nothing, if the manifest is not schema
version 1, an image is missing, a digest is malformed, or (with --sums) the manifest does
not match the release's SHA256SUMS.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

SCHEMA_VERSION = 1
# release-manifest.json service name -> key under the chart's `images`.
SERVICES = {
    "api": "api",
    "worker": "worker",
    "web": "web",
    "scenario-engine": "scenarioEngine",
    "ai-orchestrator": "aiOrchestrator",
}
DIGEST = re.compile(r"^sha256:[0-9a-f]{64}$")
# A conservative reference grammar: registry/path components, no tag, no digest.
REPOSITORY = re.compile(r"^[a-z0-9]+(?:[._-][a-z0-9]+)*(?::[0-9]+)?(?:/[a-z0-9]+(?:[._-][a-z0-9]+)*)+$")
VERSION = re.compile(r"^v\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$")


class ManifestError(ValueError):
    """The manifest cannot be turned into values."""


def check_sums(manifest_path: Path, sums_path: Path) -> None:
    """The manifest's SHA-256 must be the one SHA256SUMS lists for it."""
    want = None
    for line in sums_path.read_text(encoding="utf-8").splitlines():
        parts = line.split()
        if len(parts) == 2 and parts[1].lstrip("*") == manifest_path.name:
            want = parts[0].lower()
    if want is None:
        raise ManifestError(f"{sums_path} has no line for {manifest_path.name}")
    got = hashlib.sha256(manifest_path.read_bytes()).hexdigest()
    if got != want:
        raise ManifestError(f"{manifest_path.name}: sha256 {got} does not match SHA256SUMS ({want})")


def images_from_manifest(manifest: dict) -> tuple[str, dict[str, dict[str, str]]]:
    """(version, {chart image key: {repository, digest}}) from a parsed manifest."""
    if manifest.get("schema_version") != SCHEMA_VERSION:
        raise ManifestError(f"schema_version {manifest.get('schema_version')!r} is not {SCHEMA_VERSION}")
    version = manifest.get("version", "")
    if not isinstance(version, str) or not VERSION.match(version):
        raise ManifestError(f"version {version!r} is not vX.Y.Z[-suffix]")
    images = manifest.get("images")
    if not isinstance(images, dict):
        raise ManifestError("images is missing")
    out: dict[str, dict[str, str]] = {}
    for service, key in SERVICES.items():
        entry = images.get(service)
        if not isinstance(entry, dict):
            raise ManifestError(f"images.{service} is missing")
        repo, digest = entry.get("image", ""), entry.get("digest", "")
        if not isinstance(repo, str) or not REPOSITORY.match(repo):
            raise ManifestError(f"images.{service}.image {repo!r} is not a repository")
        if not isinstance(digest, str) or not DIGEST.match(digest):
            raise ManifestError(f"images.{service}.digest {digest!r} is not sha256:<64 hex>")
        ref = entry.get("ref")
        if ref is not None and ref != f"{repo}@{digest}":
            raise ManifestError(f"images.{service}.ref {ref!r} disagrees with image@digest")
        out[key] = {"repository": repo, "digest": digest}
    return version, out


def render(version: str, images: dict[str, dict[str, str]]) -> str:
    """The values file. Every scalar is double-quoted; none needs escaping (checked above)."""
    lines = [
        f"# Generated by infra/k8s/scripts/values_from_manifest.py from release {version}.",
        f'version: "{version}"',
        "images:",
    ]
    for key in SERVICES.values():
        img = images[key]
        lines += [
            f"  {key}:",
            f'    repository: "{img["repository"]}"',
            f'    digest: "{img["digest"]}"',
        ]
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("manifest", type=Path, help="release-manifest.json")
    parser.add_argument("--sums", type=Path, help="the same release's SHA256SUMS; verify the manifest first")
    args = parser.parse_args(argv)
    try:
        if args.sums:
            check_sums(args.manifest, args.sums)
        version, images = images_from_manifest(json.loads(args.manifest.read_text(encoding="utf-8")))
    except (OSError, json.JSONDecodeError, ManifestError) as exc:
        print(f"values_from_manifest: {exc}", file=sys.stderr)
        return 1
    sys.stdout.write(render(version, images))
    return 0


if __name__ == "__main__":
    sys.exit(main())
