---
# ansible-galaxy collection install -r requirements.yml
collections:
  - name: community.docker # docker_compose_v2
    version: ">=3.4.0"
  - name: community.crypto # self-signed TLS, certificate inspection
    version: ">=2.16.0"
  - name: community.general
    version: ">=8.0.0"
  - name: ansible.posix # sysctl, synchronize
    version: ">=1.5.0"
