import * as joint from '@joint/core';
import { firstValueFrom, Observable, of, throwError } from 'rxjs';
import { upgradeDiagramJson } from './diagram-compat';
import {
  importTemplateYaml,
  MAX_IMPORT_BYTES,
  precheckYamlText,
  TemplateImportError,
  templateToDiagram,
  TemplateValidation,
  YamlImportOutcome,
} from './range-designer-yaml-import';

/**
 * What Export YAML produces for a two-zone diagram (firewall, DC with roles,
 * workstation, Kali, a DMZ web server with extra keys, plus a switch and a link that
 * export drops). Generated by running control-plane/api range_topology.diagram_to_template
 * on that diagram, i.e. the real server export, not a hand-written guess.
 */
function exportedTemplate(): Record<string, any> {
  return {
    name: 'Round Trip Range',
    version: '1.0',
    network: {
      vlans: [
        { id: 10, name: 'corp-lan', cidr: '10.10.0.0/24' },
        { gateway: '172.16.0.1', id: 20, name: 'dmz', cidr: '172.16.0.0/24' },
      ],
    },
    nodes: [
      { id: 'edge-fw', name: 'Edge FW', role: 'firewall', os: 'pfsense', vlan: 'corp-lan', ip: '10.10.0.1',
        specs: { cores: 2, memory_mb: 2048, disk_gb: 20 } },
      { id: 'dc01', name: 'DC01', role: 'domain_controller', os: 'windows-server-2022', vlan: 'corp-lan',
        ip: '10.10.0.10', specs: { cores: 4, memory_mb: 8192, disk_gb: 120 }, services: ['ad-ds', 'dns'] },
      { id: 'ws01', name: 'WS01', role: 'workstation', os: 'windows-11', vlan: 'corp-lan', ip: '10.10.0.50',
        specs: { cores: 2, memory_mb: 4096, disk_gb: 60 } },
      { id: 'kali', name: 'Kali', role: 'attack_platform', os: 'kali-2024', vlan: 'corp-lan',
        specs: { cores: 2, memory_mb: 4096, disk_gb: 80 } },
      { tags: ['public'], id: 'web1', name: 'Web 1', role: 'server', os: 'ubuntu-24.04', vlan: 'dmz',
        ip: '172.16.0.20', specs: { nested_hv: true, cores: 2, memory_mb: 2048, disk_gb: 40 } },
    ],
    source: { tool: 'range-designer' },
  };
}

const EXPORTED_YAML = 'name: Round Trip Range\nversion: \'1.0\'\nnodes:\n- id: edge-fw\n';

/** A stand-in for ApiService.validateTemplate that records what it was sent. */
function fakeValidator(response: TemplateValidation | Observable<TemplateValidation>) {
  const calls: string[] = [];
  const fn = (yaml: string) => {
    calls.push(yaml);
    return response instanceof Observable ? response : of(response);
  };
  return { fn, calls };
}

const ok = (normalized: Record<string, any>, warnings: string[] = []): TemplateValidation =>
  ({ valid: true, errors: [], normalized, warnings });

function byHostname(cells: Record<string, any>[]): Record<string, Record<string, any>> {
  return Object.fromEntries(cells.filter(c => c['nodeData']?.hostname).map(c => [c['nodeData'].hostname, c]));
}

describe('range designer YAML import', () => {
  describe('round trip: export -> import', () => {
    it('restores every zone and node with its OS, specs, services, IP and VLAN', () => {
      const { diagram, nodeCount, zoneCount, notes } = templateToDiagram(exportedTemplate());

      expect(zoneCount).toBe(2);
      expect(nodeCount).toBe(5);
      expect(notes).toEqual([]);

      const zones = diagram.cells.filter(c => c['nodeType'] === 'subnet' || c['nodeType'] === 'dmz');
      expect(zones.map(z => [z['nodeType'], z['nodeData']])).toEqual([
        ['subnet', { label: 'corp-lan', cidr: '10.10.0.0/24', vlan: 10 }],
        ['dmz', { label: 'dmz', cidr: '172.16.0.0/24', vlan: 20, template_extra: { gateway: '172.16.0.1' } }],
      ]);

      const n = byHostname(diagram.cells);
      expect(n['edge-fw']['nodeType']).toBe('firewall');
      expect(n['dc01']['nodeType']).toBe('dc');
      expect(n['ws01']['nodeType']).toBe('workstation');
      expect(n['kali']['nodeType']).toBe('kali'); // role attack_platform -> by OS
      expect(n['web1']['nodeType']).toBe('server');

      expect(n['dc01']['nodeData']).toEqual({
        label: 'DC01', hostname: 'dc01', ip: '10.10.0.10', os_template: 'windows-server-2022',
        role: 'domain_controller', vcpu: '4', ram_mb: '8192', disk_gb: '120', vlan: '10', services: 'ad-ds,dns',
      });
      // Keys the designer has no field for ride along so export puts them back.
      expect(n['web1']['nodeData']['template_extra']).toEqual({ tags: ['public'], specs: { nested_hv: true } });
      expect(n['web1']['nodeData']['vlan']).toBe('20');
    });

    it('places each node inside its own zone, so export assigns the same VLAN again', () => {
      const { diagram } = templateToDiagram(exportedTemplate());
      const zones = diagram.cells.filter(c => c['nodeType'] === 'subnet' || c['nodeType'] === 'dmz');
      const inside = (node: any, zone: any) => {
        const cx = node.position.x + node.size.width / 2;
        const cy = node.position.y + node.size.height / 2;
        return cx >= zone.position.x && cx <= zone.position.x + zone.size.width
          && cy >= zone.position.y && cy <= zone.position.y + zone.size.height;
      };
      for (const node of exportedTemplate()['nodes']) {
        const cell = byHostname(diagram.cells)[node.id];
        const owners = zones.filter(z => inside(cell, z)).map(z => z['nodeData'].label);
        expect(owners).withContext(node.id).toEqual([node.vlan]);
      }
    });

    it('produces JSON JointJS can load, with unique cell ids', () => {
      const { diagram } = templateToDiagram(exportedTemplate());
      const graph = new joint.dia.Graph({}, { cellNamespace: joint.shapes });
      graph.fromJSON(upgradeDiagramJson(diagram) as any);

      expect(graph.getElements().length).toBe(7);
      const ids = diagram.cells.map(c => c['id']);
      expect(new Set(ids).size).toBe(ids.length);
      expect(graph.getCell('dc01').prop('nodeData/os_template')).toBe('windows-server-2022');
    });

    it('runs the file through the server validator and loads the normalized document', async () => {
      const v = fakeValidator(ok(exportedTemplate(), ['dc01: raised to the minimum for ad-ds']));
      const out = await firstValueFrom(importTemplateYaml(EXPORTED_YAML, v.fn));

      expect(v.calls).toEqual([EXPORTED_YAML]);
      expect(out.ok).toBeTrue();
      const success = out as Extract<YamlImportOutcome, { ok: true }>;
      expect(success.nodeCount).toBe(5);
      expect(success.warnings).toEqual(['dc01: raised to the minimum for ad-ds']);
    });
  });

  describe('invalid YAML', () => {
    it('reports the parser error and loads nothing', async () => {
      const v = fakeValidator({
        valid: false,
        normalized: null,
        errors: [{ path: '', message: 'Invalid YAML: mapping values are not allowed here\n  in "<unicode string>", line 3, column 9' }],
      });
      const out = await firstValueFrom(importTemplateYaml('name: x\nnodes:\n  - id: a: b\n', v.fn));

      expect(out).toEqual({
        ok: false,
        title: 'The file is not valid YAML',
        messages: ['Invalid YAML: mapping values are not allowed here\n  in "<unicode string>", line 3, column 9'],
      });
    });

    it('reports a document that is not a mapping', async () => {
      const v = fakeValidator({ valid: false, normalized: null, errors: [{ path: '', message: 'Document must be a YAML mapping' }] });
      const out = await firstValueFrom(importTemplateYaml('- just\n- a list\n', v.fn));
      expect(out.ok).toBeFalse();
      expect((out as any).messages).toEqual(['Document must be a YAML mapping']);
    });

    it('rejects empty, oversized and binary files without calling the server', async () => {
      const v = fakeValidator(ok(exportedTemplate()));
      for (const text of ['', '   \n\t\n', 'a'.repeat(MAX_IMPORT_BYTES + 1), 'name: x\u0000']) {
        const out = await firstValueFrom(importTemplateYaml(text, v.fn));
        expect(out.ok).toBeFalse();
        expect((out as any).title).toBe('Cannot import this file');
      }
      expect(v.calls).toEqual([]);
      expect(precheckYamlText('name: fine\n')).toBeNull();
    });
  });

  describe('server validation errors', () => {
    it('surfaces every schema and role error with its path, and loads nothing', async () => {
      const v = fakeValidator({
        valid: false,
        normalized: { nodes: [{ id: 'dc', os: 'windows-server-2022' }] },
        errors: [
          { path: '', message: "'name' is a required property" },
          { path: 'nodes', message: 'dc: Exchange and AD DS cannot share one VM' },
        ],
      });
      const out = await firstValueFrom(importTemplateYaml('nodes:\n- id: dc\n', v.fn));

      expect(out).toEqual({
        ok: false,
        title: 'The template failed validation',
        messages: ["'name' is a required property", 'nodes: dc: Exchange and AD DS cannot share one VM'],
      });
    });

    it('treats a failed validate request as a failure, not as an empty template', async () => {
      const cases: [any, string][] = [
        [{ status: 0 }, 'The control plane could not be reached.'],
        [{ status: 403, error: {} }, 'You do not have permission to validate templates.'],
        [{ status: 422, error: { detail: 'template YAML refused: document uses YAML aliases' } },
          'template YAML refused: document uses YAML aliases'],
      ];
      for (const [err, message] of cases) {
        const v = fakeValidator(throwError(() => err));
        const out = await firstValueFrom(importTemplateYaml('name: x\n', v.fn));
        expect(out).toEqual({ ok: false, title: 'Could not validate the file', messages: [message] });
      }
    });

    it('does not trust valid:true when errors are present', async () => {
      const v = fakeValidator({ valid: true, normalized: exportedTemplate(), errors: [{ path: 'nodes', message: 'bad' }] });
      const out = await firstValueFrom(importTemplateYaml('name: x\n', v.fn));
      expect(out.ok).toBeFalse();
    });
  });

  describe('unknown and missing fields', () => {
    it('keeps unknown node and VLAN keys, and reports unknown top-level keys', () => {
      const { diagram, notes } = templateToDiagram({
        name: 'x',
        description: 'kept by the template editor, not the designer',
        policies: { egress: 'none' },
        network: { vlans: [{ id: 5, name: 'lab', cidr: '10.5.0.0/24', mtu: 9000 }] },
        nodes: [{ id: 'a', os: 'ubuntu-24.04', vlan: 'lab', cloud_init: { packages: ['nginx'] } }],
      });
      expect(notes).toEqual(['Not shown in the designer and not kept on export: description, policies']);
      expect(diagram.cells[0]['nodeData']['template_extra']).toEqual({ mtu: 9000 });
      expect(byHostname(diagram.cells)['a']['nodeData']['template_extra']).toEqual({ cloud_init: { packages: ['nginx'] } });
    });

    it('fills in missing fields with the same defaults as the server', () => {
      const { diagram, notes, zoneCount } = templateToDiagram({
        name: 'sparse',
        nodes: [{ name: 'Box' }, { os: 'windows-11' }, { id: 'dc', role: 'dc', os: 'windows-server-2022', vlan: 'corp' }],
      });
      const n = byHostname(diagram.cells);

      // No network: one zone per VLAN the nodes name, plus "default" for those that name none.
      expect(zoneCount).toBe(2);
      expect(diagram.cells.slice(0, 2).map(c => c['nodeData'].label)).toEqual(['corp', 'default']);
      expect(diagram.cells[0]['nodeData'].cidr).toBe('');
      expect(diagram.cells[0]['nodeData'].vlan).toBeUndefined();

      expect(n['Box']['nodeType']).toBe('server');
      expect(n['Box']['nodeData'].os_template).toBe('');
      expect(n['node']['nodeType']).toBe('workstation'); // no id or name: "node", typed by OS
      expect(n['dc']['nodeType']).toBe('dc');
      expect(notes).toEqual([
        'Box: no os set; export will skip it until an OS template is chosen',
      ]);
    });

    it('expands count into separate nodes without IPs, and keeps cell ids unique', () => {
      const { diagram, nodeCount } = templateToDiagram({
        name: 'x',
        nodes: [
          { id: 'ws', os: 'windows-11', count: 3, ip: '10.0.0.5' },
          { id: 'ws-0', os: 'windows-11' },
        ],
      });
      expect(nodeCount).toBe(4);
      const nodes = diagram.cells.filter(c => c['nodeData'].hostname);
      expect(nodes.map(c => c['nodeData'].hostname)).toEqual(['ws-0', 'ws-1', 'ws-2', 'ws-0']);
      expect(nodes.slice(0, 3).every(c => c['nodeData'].ip === '')).toBeTrue();
      const ids = diagram.cells.map(c => c['id']);
      expect(new Set(ids).size).toBe(ids.length);
    });

    it('skips malformed entries and reports them', () => {
      const { nodeCount, notes } = templateToDiagram({
        name: 'x',
        nodes: [{ id: 'a', os: 'kali-2024', count: 'lots' }, 'not-a-mapping', 42],
      });
      expect(nodeCount).toBe(1);
      expect(notes).toContain('a: count "lots" is not a number; imported once');
      expect(notes).toContain('2 node entries were not a mapping; skipped');
    });

    it('refuses a count that would exceed the designer limit', () => {
      expect(() => templateToDiagram({ name: 'x', nodes: [{ id: 'a', os: 'kali-2024', count: 100000 }] }))
        .toThrowError(TemplateImportError, /more than 2000/);
    });

    it('draws an assets-only template as a starter sketch', () => {
      const { diagram, nodeCount, notes } = templateToDiagram({
        name: 'assets',
        assets: [{ role: 'dc', type: 'vm', count: 1 }, { role: 'client', type: 'vm', count: 2 }],
      });
      expect(nodeCount).toBe(4); // gateway + 3 hosts
      expect(diagram.cells.map(c => c['nodeType'])).toEqual(['firewall', 'subnet', 'dc', 'workstation', 'workstation']);
      expect(notes.some(n => n.startsWith('Assets-style template'))).toBeTrue();
    });

    it('reports a template with nothing to draw instead of loading a blank canvas', async () => {
      expect(() => templateToDiagram({ name: 'empty' })).toThrowError(TemplateImportError);
      const out = await firstValueFrom(importTemplateYaml('name: empty\n', fakeValidator(ok({ name: 'empty' })).fn));
      expect(out).toEqual({
        ok: false,
        title: 'Nothing to import',
        messages: ['The template declares no nodes or assets, so there is nothing to draw.'],
      });
    });
  });
});
